/* eslint-disable @typescript-eslint/no-explicit-any -- PostgreSQL rows are mapped to the versioned Clinic API contract. */
import type { PoolClient } from 'pg';
import { pool } from '../database/pool.js';
import { AppError } from '../lib/errors.js';

const audit=(client:PoolClient,userId:string,action:string,targetId:string,metadata:Record<string,unknown>={})=>client.query(`INSERT INTO audit_events(actor_user_id,action,target_type,target_id,outcome,metadata)VALUES($1,$2,'clinic_encounter',$3,'success',$4)`,[userId,action,targetId,JSON.stringify(metadata)]);

export const consultationRepository={
 async detail(encounterId:string){
  const encounter=await pool.query(`SELECT e.id,e.encounter_number "encounterNumber",e.student_id "studentId",e.encounter_date "encounterDate",e.time_in "timeIn",e.time_out "timeOut",e.grade_level_snapshot "gradeLevel",e.section_snapshot section,e.source,e.chief_complaint "chiefComplaint",e.symptoms,e.temperature_c::float "temperatureC",e.blood_pressure "bloodPressure",e.pulse,e.respiratory_rate "respiratoryRate",e.oxygen_saturation::float "oxygenSaturation",e.weight_kg::float "weightKg",e.assessment,e.diagnosis,e.treatment,e.observation_notes "observationNotes",e.clinical_notes "clinicalNotes",e.disposition,e.queue_status "queueStatus",e.follow_up_required "followUpRequired",e.parent_contact_required "parentContactRequired",s.student_number "studentNumber",s.first_name "firstName",s.last_name "lastName",s.profile_photo_url "profilePhotoUrl",u.display_name "clinicStaff" FROM clinic_encounters e JOIN students s ON s.id=e.student_id JOIN users u ON u.id=e.clinic_staff_user_id WHERE e.id=$1`,[encounterId]);
  if(!encounter.rows[0])throw new AppError(404,'ENCOUNTER_NOT_FOUND','Clinic encounter not found');const studentId=encounter.rows[0].studentId;
  const[alerts,guardians,interventions,medications,contacts,followUps]=await Promise.all([
   pool.query(`SELECT id,alert_type "alertType",severity,title,notes FROM clinic_health_alerts WHERE student_id=$1 AND active ORDER BY severity DESC,created_at DESC`,[studentId]),
   pool.query(`SELECT g.id,g.first_name "firstName",g.last_name "lastName",g.mobile_phone "mobilePhone",sg.relationship_type "relationshipType",sg.is_primary "isPrimary" FROM student_guardians sg JOIN guardians g ON g.id=sg.guardian_id WHERE sg.student_id=$1 AND sg.archived_at IS NULL AND g.archived_at IS NULL ORDER BY sg.is_primary DESC,g.last_name`,[studentId]),
   pool.query(`SELECT i.id,i.intervention_type "interventionType",i.notes,i.performed_at "performedAt",u.display_name "performedBy" FROM clinic_interventions i JOIN users u ON u.id=i.performed_by WHERE i.encounter_id=$1 ORDER BY i.performed_at`,[encounterId]),
   pool.query(`SELECT t.id,t.item_id "itemId",i.name,i.unit,t.quantity::float,t.dose,t.route,t.instructions,t.created_at "administeredAt",l.lot_number "lotNumber",l.expiration_date "expirationDate" FROM clinic_inventory_transactions t JOIN clinic_items i ON i.id=t.item_id LEFT JOIN clinic_inventory_lots l ON l.id=t.lot_id WHERE t.encounter_id=$1 AND t.transaction_type='dispense' ORDER BY t.created_at`,[encounterId]),
   pool.query(`SELECT c.id,c.contacted_at "contactedAt",c.method,c.reason,c.result,c.acknowledged,c.notes,g.first_name "firstName",g.last_name "lastName" FROM clinic_guardian_contacts c JOIN guardians g ON g.id=c.guardian_id WHERE c.encounter_id=$1 ORDER BY c.contacted_at`,[encounterId]),
   pool.query(`SELECT id,due_date "dueDate",reason,instructions,status FROM clinic_follow_ups WHERE originating_encounter_id=$1 ORDER BY due_date`,[encounterId]),
  ]);
  return{encounter:encounter.rows[0],alerts:alerts.rows,guardians:guardians.rows,interventions:interventions.rows,medications:medications.rows,guardianContacts:contacts.rows,followUps:followUps.rows};
 },
 async availableStock(){return(await pool.query(`SELECT i.id "itemId",i.name,i.code,i.unit,COALESCE(sum(l.quantity_remaining) FILTER(WHERE l.expiration_date IS NULL OR l.expiration_date>=current_date),0)::float "availableStock",json_agg(json_build_object('lotId',l.id,'lotNumber',l.lot_number,'expirationDate',l.expiration_date,'quantity',l.quantity_remaining::float) ORDER BY l.expiration_date NULLS LAST,l.received_on) FILTER(WHERE l.quantity_remaining>0 AND (l.expiration_date IS NULL OR l.expiration_date>=current_date)) "validLots" FROM clinic_items i LEFT JOIN clinic_inventory_lots l ON l.item_id=i.id WHERE i.active GROUP BY i.id HAVING COALESCE(sum(l.quantity_remaining) FILTER(WHERE l.expiration_date IS NULL OR l.expiration_date>=current_date),0)>0 ORDER BY i.name`)).rows},
 async addIntervention(encounterId:string,input:any,userId:string){const c=await pool.connect();try{await c.query('BEGIN');const encounter=await c.query(`SELECT id FROM clinic_encounters WHERE id=$1 AND queue_status<>'completed' FOR UPDATE`,[encounterId]);if(!encounter.rows[0])throw new AppError(409,'ENCOUNTER_NOT_ACTIVE','The encounter is completed or unavailable');const row=await c.query(`INSERT INTO clinic_interventions(encounter_id,intervention_type,notes,performed_by)VALUES($1,$2,$3,$4)RETURNING id,performed_at "performedAt"`,[encounterId,input.interventionType,input.notes??null,userId]);await audit(c,userId,'clinic.intervention.created',encounterId,{interventionType:input.interventionType});await c.query('COMMIT');return row.rows[0]}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}},
 async complete(encounterId:string,input:any,userId:string){const c=await pool.connect();try{await c.query('BEGIN');const encounter=await c.query(`SELECT id,student_id FROM clinic_encounters WHERE id=$1 AND queue_status<>'completed' FOR UPDATE`,[encounterId]);if(!encounter.rows[0])throw new AppError(409,'ENCOUNTER_NOT_ACTIVE','The encounter is already completed or unavailable');if(input.guardianContact){const linked=await c.query(`SELECT 1 FROM student_guardians WHERE student_id=$1 AND guardian_id=$2 AND archived_at IS NULL`,[encounter.rows[0].student_id,input.guardianContact.guardianId]);if(!linked.rows[0])throw new AppError(400,'INVALID_GUARDIAN','Guardian is not actively linked to this student');await c.query(`INSERT INTO clinic_guardian_contacts(student_id,encounter_id,guardian_id,method,reason,result,acknowledged,notes,contacted_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[encounter.rows[0].student_id,encounterId,input.guardianContact.guardianId,input.guardianContact.method,input.guardianContact.reason,input.guardianContact.result??null,input.guardianContact.acknowledged,input.guardianContact.notes??null,userId])}if(input.followUp){await c.query(`INSERT INTO clinic_follow_ups(student_id,originating_encounter_id,due_date,reason,instructions,created_by)VALUES($1,$2,$3,$4,$5,$6)`,[encounter.rows[0].student_id,encounterId,input.followUp.dueDate,input.followUp.reason,input.followUp.instructions??null,userId])}await c.query(`UPDATE clinic_encounters SET assessment=COALESCE($2,assessment),diagnosis=COALESCE($3,diagnosis),treatment=COALESCE($4,treatment),observation_notes=COALESCE($5,observation_notes),clinical_notes=COALESCE($6,clinical_notes),disposition=$7,follow_up_required=$8,parent_contact_required=$9,queue_status='completed',time_out=now(),updated_at=now() WHERE id=$1`,[encounterId,input.assessment??null,input.diagnosis??null,input.treatment??null,input.observationNotes??null,input.clinicalNotes??null,input.disposition,!!input.followUp,!!input.guardianContact]);await audit(c,userId,'clinic.encounter.completed',encounterId,{disposition:input.disposition,followUpCreated:!!input.followUp,guardianContactRecorded:!!input.guardianContact});await c.query('COMMIT');return{ok:true}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}},
 async dailyLog(filters:{date:string;search?:string|undefined;status?:string|undefined;disposition?:string|undefined;page:number;pageSize:number}){const values:any[]=[filters.date];const where=[`e.encounter_date=$1`];if(filters.search){values.push(`%${filters.search}%`);where.push(`(s.student_number ILIKE $${values.length} OR concat_ws(' ',s.first_name,s.last_name) ILIKE $${values.length})`)}if(filters.status){values.push(filters.status);where.push(`e.queue_status=$${values.length}`)}if(filters.disposition){values.push(filters.disposition);where.push(`e.disposition=$${values.length}`)}const count=await pool.query(`SELECT count(*)::int total FROM clinic_encounters e JOIN students s ON s.id=e.student_id WHERE ${where.join(' AND ')}`,values);values.push(filters.pageSize,(filters.page-1)*filters.pageSize);const rows=await pool.query(`SELECT e.id,e.encounter_number "encounterNumber",e.encounter_date "encounterDate",e.time_in "timeIn",e.time_out "timeOut",e.grade_level_snapshot "gradeLevel",e.section_snapshot section,e.chief_complaint "chiefComplaint",e.queue_status "queueStatus",e.disposition,s.student_number "studentNumber",s.first_name "firstName",s.last_name "lastName",u.display_name "clinicStaff" FROM clinic_encounters e JOIN students s ON s.id=e.student_id JOIN users u ON u.id=e.clinic_staff_user_id WHERE ${where.join(' AND ')} ORDER BY e.time_in DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);return{items:rows.rows,total:count.rows[0].total,page:filters.page,pageSize:filters.pageSize}},
};
