import { beforeEach, describe, expect, it, vi } from 'vitest';
const state=vi.hoisted(()=>({stock:1,locked:false,waiters:[] as (()=>void)[],queries:[] as string[]}));
vi.mock('../database/pool.js',()=>({pool:{connect:vi.fn(async()=>{let owns=false;const acquire=async()=>{if(!state.locked){state.locked=true;owns=true;return}await new Promise<void>(resolve=>state.waiters.push(resolve));state.locked=true;owns=true};const release=()=>{if(!owns)return;owns=false;state.locked=false;state.waiters.shift()?.()};return{query:vi.fn(async(sql:string,params?:unknown[])=>{state.queries.push(sql);if(sql==='BEGIN')return{rows:[],rowCount:null};if(sql.includes('FROM clinic_encounters'))return{rows:[{id:'encounter'}],rowCount:1};if(sql.includes('FROM clinic_items')){await acquire();return{rows:[{id:'item',active:true}],rowCount:1}}if(sql.includes('FROM clinic_inventory_lots'))return{rows:state.stock>0?[{id:'lot',quantity_remaining:state.stock,expiration_date:'2026-12-01'}]:[],rowCount:state.stock>0?1:0};if(sql.includes('UPDATE clinic_inventory_lots')){state.stock-=Number(params?.[0]);return{rows:[],rowCount:1}}if(sql==='COMMIT'||sql==='ROLLBACK'){release();return{rows:[],rowCount:null}}return{rows:[{id:'row'}],rowCount:1}}),release:vi.fn(release)}})}}));
import { clinicRepository } from './repository.js';

describe('Clinic transactional dispensing',()=>{beforeEach(()=>{state.stock=1;state.locked=false;state.waiters=[];state.queries=[]});
 it('excludes expired lots and orders eligible stock by earliest expiry under row lock',async()=>{await clinicRepository.dispense('encounter',{itemId:'item',quantity:1},'user');const lotQuery=state.queries.find(x=>x.includes('FROM clinic_inventory_lots'))||'';expect(lotQuery).toContain('expiration_date>=current_date');expect(lotQuery).toContain('ORDER BY expiration_date NULLS LAST');expect(lotQuery).toContain('FOR UPDATE')});
 it('rolls back when requested quantity exceeds unexpired stock',async()=>{await expect(clinicRepository.dispense('encounter',{itemId:'item',quantity:2},'user')).rejects.toMatchObject({code:'INSUFFICIENT_STOCK'});expect(state.queries).toContain('ROLLBACK');expect(state.queries).not.toContain('COMMIT')});
 it('allows only one of two concurrent requests to consume the last unit',async()=>{const results=await Promise.allSettled([clinicRepository.dispense('encounter',{itemId:'item',quantity:1},'user-a'),clinicRepository.dispense('encounter',{itemId:'item',quantity:1},'user-b')]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);const rejected=results.find(x=>x.status==='rejected') as PromiseRejectedResult;expect(rejected.reason).toMatchObject({code:'INSUFFICIENT_STOCK'});expect(state.stock).toBe(0)});
});
