import { z } from 'zod';

export const id = z.string().uuid();
const optionalText = (max: number) => z.string().trim().max(max).optional().nullable();
const version = z.number().int().positive();

export const healthProfileUpdate = z.object({
  bloodType: z.enum(['A+','A-','B+','B-','AB+','AB-','O+','O-','unknown']).optional().nullable(),
  pastIllnesses: optionalText(5000), surgeriesHospitalizations: optionalText(5000),
  medicationRestrictions: optionalText(5000), longTermMedications: optionalText(5000),
  emergencyNotes: optionalText(5000), physicianRecommendations: optionalText(5000), version: version.optional(),
});
export const alertCreate = z.object({alertType:z.enum(['allergy','medical_condition','medication_restriction','emergency_instruction']),severity:z.enum(['low','moderate','high','critical']),title:z.string().trim().min(1).max(160),notes:optionalText(3000),active:z.boolean().default(true)});
export const alertUpdate = alertCreate.partial().extend({version});
export const immunizationCreate = z.object({vaccineName:z.string().trim().min(1).max(160),dose:optionalText(80),administeredOn:z.string().date(),provider:optionalText(200),notes:optionalText(3000)});
export const immunizationUpdate = immunizationCreate.partial().extend({version});
const optionalVital = (min:number,max:number) => z.number().min(min).max(max).optional().nullable();
export const physicalExamCreate = z.object({examinedOn:z.string().date(),heightCm:optionalVital(30,250),weightKg:optionalVital(1,500),temperatureC:optionalVital(25,45),systolic:optionalVital(40,300),diastolic:optionalVital(20,200),pulse:optionalVital(20,250),respiratoryRate:optionalVital(5,80),visionNotes:optionalText(3000),hearingNotes:optionalText(3000),dentalNotes:optionalText(3000),findings:optionalText(5000),recommendations:optionalText(5000),notes:optionalText(3000)});
export const physicalExamUpdate = physicalExamCreate.partial().extend({version});
export function calculateBmi(heightCm?:number|null,weightKg?:number|null){if(!heightCm||!weightKg||heightCm<=0||weightKg<=0)return null;return Math.round((weightKg/((heightCm/100)**2))*100)/100;}

export const encounterCreate=z.object({studentId:id,source:z.enum(['self_initiated','teacher_referral','staff_referral','pe_sports','school_activity','injury','scheduled_visit','follow_up','other']),chiefComplaint:z.string().trim().min(1).max(3000),symptoms:z.array(z.string().trim().min(1).max(100)).max(20).default([]),temperatureC:z.number().min(25).max(45).optional(),bloodPressure:z.string().max(20).optional(),pulse:z.number().int().min(20).max(250).optional(),respiratoryRate:z.number().int().min(5).max(80).optional(),oxygenSaturation:z.number().min(40).max(100).optional(),assessment:z.string().max(5000).optional()});
export const encounterUpdate=z.object({queueStatus:z.enum(['waiting','in_consultation','under_observation','ready_for_disposition']).optional(),chiefComplaint:z.string().trim().min(1).max(3000).optional(),symptoms:z.array(z.string().trim().min(1).max(100)).max(20).optional(),temperatureC:z.number().min(25).max(45).optional().nullable(),bloodPressure:z.string().trim().max(20).optional().nullable(),pulse:z.number().int().min(20).max(250).optional().nullable(),respiratoryRate:z.number().int().min(5).max(80).optional().nullable(),oxygenSaturation:z.number().min(40).max(100).optional().nullable(),weightKg:z.number().min(1).max(500).optional().nullable(),assessment:z.string().max(5000).optional().nullable(),diagnosis:z.string().max(3000).optional().nullable(),treatment:z.string().max(5000).optional().nullable(),observationNotes:z.string().max(5000).optional().nullable(),clinicalNotes:z.string().max(8000).optional().nullable(),disposition:z.enum(['returned_to_class','rested_and_returned','sent_home','guardian_pickup','physician_referral','hospital_referral','emergency_response','follow_up_required','other']).optional().nullable(),followUpRequired:z.boolean().optional(),parentContactRequired:z.boolean().optional()});
export const interventionCreate=z.object({interventionType:z.enum(['rest','hydration','wound_cleaning','dressing','ice_pack','first_aid','medication','monitoring','parent_contacted','referral','other']),notes:z.string().trim().max(3000).optional().nullable()});
export const encounterComplete=z.object({disposition:z.enum(['returned_to_class','rested_and_returned','sent_home','guardian_pickup','physician_referral','hospital_referral','emergency_response','follow_up_required','other']),assessment:z.string().max(5000).optional().nullable(),diagnosis:z.string().max(3000).optional().nullable(),treatment:z.string().max(5000).optional().nullable(),observationNotes:z.string().max(5000).optional().nullable(),clinicalNotes:z.string().max(8000).optional().nullable(),followUp:z.object({dueDate:z.string().date(),reason:z.string().trim().min(1).max(2000),instructions:z.string().max(3000).optional().nullable()}).optional(),guardianContact:z.object({guardianId:id,method:z.enum(['phone','sms','email','in_person','other']),reason:z.string().trim().min(1).max(2000),result:z.string().max(2000).optional().nullable(),acknowledged:z.boolean().default(false),notes:z.string().max(3000).optional().nullable()}).optional()});
export const itemCreate=z.object({code:z.string().trim().min(1).max(50),name:z.string().trim().min(1).max(180),genericName:z.string().max(180).nullable().optional(),brandName:z.string().max(180).nullable().optional(),category:z.string().trim().min(1).max(80),description:z.string().max(3000).nullable().optional(),unit:z.string().trim().min(1).max(40),reorderLevel:z.number().min(0).default(0),requiresLot:z.boolean().default(false),active:z.boolean().default(true)});
export const stockIn=z.object({quantity:z.number().positive(),lotNumber:z.string().max(100).optional(),expirationDate:z.string().date().optional(),supplierReference:z.string().max(160).optional(),reason:z.string().max(1000).optional()});
export const dispense=z.object({itemId:id,quantity:z.number().positive(),dose:z.string().max(100).optional(),route:z.string().max(80).optional(),instructions:z.string().max(2000).optional(),notes:z.string().max(3000).optional()});
export const followUp=z.object({dueDate:z.string().date(),reason:z.string().trim().min(1).max(2000),instructions:z.string().max(3000).optional(),assignedUserId:id.optional()});
export const guardianContact=z.object({guardianId:id,method:z.enum(['phone','sms','email','in_person','other']),reason:z.string().trim().min(1).max(2000),result:z.string().max(2000).optional(),acknowledged:z.boolean().default(false),notes:z.string().max(3000).optional()});
export const appointmentCreate=z.object({studentId:id,appointmentType:z.string().trim().min(1).max(100),scheduledAt:z.string().datetime(),reason:z.string().trim().min(1).max(2000),assignedUserId:id.optional().nullable(),notes:z.string().max(3000).optional().nullable()});
export const appointmentUpdate=appointmentCreate.omit({studentId:true}).partial().extend({version:z.number().int().positive(),status:z.enum(['scheduled','completed','cancelled','missed','rescheduled']).optional(),encounterId:id.optional().nullable()});
export const followUpCreate=z.object({studentId:id,originatingEncounterId:id,dueDate:z.string().date(),reason:z.string().trim().min(1).max(2000),instructions:z.string().max(3000).optional().nullable(),assignedUserId:id.optional().nullable(),notes:z.string().max(3000).optional().nullable()});
export const followUpUpdate=followUpCreate.omit({studentId:true,originatingEncounterId:true}).partial().extend({version:z.number().int().positive(),status:z.enum(['pending','completed','cancelled','overdue']).optional(),completionEncounterId:id.optional().nullable()});
export const portalReleaseCreate=z.object({studentId:id,encounterId:id.optional().nullable(),appointmentId:id.optional().nullable(),followUpId:id.optional().nullable(),audience:z.enum(['student','guardians','both']),category:z.enum(['visit_notice','pickup_request','sent_home','appointment','follow_up','medication_concern','medical_document_request','document_request','released_instruction']).transform(value=>value==='document_request'?'medical_document_request':value),title:z.string().trim().min(1).max(160),summary:z.string().trim().min(1).max(1000),instructions:z.string().max(2000).optional().nullable()}).refine(x=>[x.encounterId,x.appointmentId,x.followUpId].filter(Boolean).length<=1,{message:'Only one source record may be linked'});
