import type {PoolClient} from 'pg';
import {pool} from '../database/pool.js';
import {AppError} from '../lib/errors.js';
import {createTemporaryPassword,hashPassword} from './crypto.js';
import {securityRepository} from './repository.js';

type Context={actorId:string;requestId:string;ip?:string|undefined};
type Kind='student'|'teacher'|'guardian';
type Result={userId:string;displayName:string;loginIdentifier:string;temporaryPassword?:string;created:boolean;status:'created'|'already_active'};
const roleFor={student:'student',teacher:'teacher',guardian:'parent_guardian'} as const;
const aliasFor={student:'student_number',teacher:'employee_number',guardian:'guardian_number'} as const;
const accountFor={student:'student',teacher:'employee',guardian:'guardian'} as const;

async function roleId(client:PoolClient,code:string){const result=await client.query<{id:string}>('SELECT id FROM roles WHERE code=$1 AND archived_at IS NULL',[code]);if(!result.rows[0])throw new AppError(500,'ROLE_NOT_CONFIGURED','Required portal role is not configured');return result.rows[0].id;}

export class ProvisioningService{
 async portalCandidates(){return (await pool.query(`SELECT candidates.*,u.status "accountStatus",u.must_change_password "mustChangePassword",portal."activationDate",portal."activationDate" IS NOT NULL "portalEnabled",u.last_login_at "lastLoginAt",u.locked_until "lockedUntil",login.normalized_value username FROM (
 SELECT 'student' kind,s.id "personId",s.student_number "identifier",concat_ws(' ',s.first_name,s.middle_name,s.last_name) "displayName",s.user_id "userId" FROM students s WHERE s.archived_at IS NULL AND s.enrollment_status='enrolled' AND EXISTS(SELECT 1 FROM enrollments e JOIN school_years sy ON sy.id=e.school_year_id WHERE e.student_id=s.id AND e.status IN('pending','enrolled') AND sy.status IN('planned','active'))
 UNION ALL SELECT 'teacher',t.id,e.employee_number,concat_ws(' ',e.first_name,e.middle_name,e.last_name),e.user_id FROM teacher_profiles t JOIN employees e ON e.id=t.employee_id WHERE t.archived_at IS NULL AND t.faculty_status<>'inactive' AND e.archived_at IS NULL AND e.employment_status IN('active','on_leave')
 UNION ALL SELECT 'guardian',g.id,g.guardian_number,concat_ws(' ',g.first_name,g.middle_name,g.last_name),g.user_id FROM guardians g WHERE g.archived_at IS NULL AND EXISTS(SELECT 1 FROM student_guardians sg JOIN students s ON s.id=sg.student_id WHERE sg.guardian_id=g.id AND sg.archived_at IS NULL AND sg.receives_communications AND s.archived_at IS NULL AND s.enrollment_status='enrolled')) candidates
 LEFT JOIN users u ON u.id=candidates."userId" AND u.archived_at IS NULL
 LEFT JOIN LATERAL(SELECT li.normalized_value FROM login_identities li WHERE li.user_id=u.id AND li.active ORDER BY (li.type='username') DESC,li.is_primary DESC LIMIT 1) login ON true
 LEFT JOIN LATERAL(SELECT ur.assigned_at "activationDate" FROM user_roles ur JOIN roles r ON r.id=ur.role_id AND r.archived_at IS NULL WHERE ur.user_id=u.id AND r.code=CASE candidates.kind WHEN 'guardian' THEN 'parent_guardian' ELSE candidates.kind END ORDER BY ur.assigned_at DESC LIMIT 1) portal ON true
 ORDER BY candidates.kind,candidates."displayName"`)).rows;}
 async employeeCandidates(search='') {const value=`%${search}%`;return (await pool.query(`SELECT e.id,e.employee_number "employeeNumber",concat_ws(' ',e.first_name,e.middle_name,e.last_name) "displayName",e.work_email "recoveryEmail",e.employment_status "employmentStatus",d.name "departmentName",p.name "positionName",EXISTS(SELECT 1 FROM teacher_profiles t WHERE t.employee_id=e.id AND t.archived_at IS NULL AND t.faculty_status<>'inactive') "isTeacher",e.user_id "userId" FROM employees e LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN positions p ON p.id=e.position_id WHERE e.archived_at IS NULL AND e.employment_status IN('active','on_leave') AND ($1='%%' OR e.employee_number ILIKE $1 OR concat_ws(' ',e.first_name,e.middle_name,e.last_name) ILIKE $1) ORDER BY e.last_name,e.first_name LIMIT 50`,[value])).rows;}

 async provisionEmployee(input:{employeeId:string;username:string;recoveryEmail:string;roleIds:string[]},ctx:Context):Promise<Result>{const client=await pool.connect();try{await client.query('BEGIN');const found=await client.query(`SELECT e.id,e.user_id,e.employee_number,e.work_email,concat_ws(' ',e.first_name,e.middle_name,e.last_name) display_name FROM employees e WHERE e.id=$1 AND e.archived_at IS NULL AND e.employment_status IN('active','on_leave') FOR UPDATE`,[input.employeeId]);const person=found.rows[0];if(!person)throw new AppError(400,'EMPLOYEE_NOT_ELIGIBLE','Select an active eligible employee');if(person.user_id)throw new AppError(409,'ACCOUNT_ALREADY_LINKED','This employee already has a centralized account');const temporaryPassword=createTemporaryPassword();const created=await client.query(`INSERT INTO users(email,display_name,password_hash,account_type,must_change_password) VALUES($1,$2,$3,'employee',true) RETURNING id`,[input.recoveryEmail,person.display_name,await hashPassword(temporaryPassword)]);const userId=String(created.rows[0].id);await client.query(`INSERT INTO login_identities(user_id,type,normalized_value,is_primary) VALUES($1,'username',$2,true)`,[userId,input.username]);await client.query('UPDATE employees SET user_id=$2,updated_at=now(),version=version+1 WHERE id=$1',[input.employeeId,userId]);for(const id of [...new Set(input.roleIds)])await client.query('INSERT INTO user_roles(user_id,role_id,assigned_by) SELECT $1,id,$3 FROM roles WHERE id=$2 AND archived_at IS NULL ON CONFLICT DO NOTHING',[userId,id,ctx.actorId]);await securityRepository.audit({actorUserId:ctx.actorId,action:'security.account.provision',targetType:'user',targetId:userId,outcome:'success',requestId:ctx.requestId,ipAddress:ctx.ip,metadata:{accountType:'employee',employeeId:input.employeeId,mustChangePassword:true}},client);await client.query('COMMIT');return{userId,displayName:String(person.display_name),loginIdentifier:input.username,temporaryPassword,created:true,status:'created'};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}

 async activate(kind:Kind,personId:string,ctx:Context):Promise<Result>{const client=await pool.connect();try{await client.query('BEGIN');let query='';if(kind==='student')query=`SELECT s.id,s.user_id,s.student_number identifier,s.personal_email email,concat_ws(' ',s.first_name,s.middle_name,s.last_name) display_name FROM students s WHERE s.id=$1 AND s.archived_at IS NULL AND s.enrollment_status='enrolled' AND EXISTS(SELECT 1 FROM enrollments e JOIN school_years sy ON sy.id=e.school_year_id WHERE e.student_id=s.id AND e.status IN('pending','enrolled') AND sy.status IN('planned','active')) FOR UPDATE`;if(kind==='teacher')query=`SELECT e.id,e.user_id,e.employee_number identifier,e.work_email email,concat_ws(' ',e.first_name,e.middle_name,e.last_name) display_name FROM teacher_profiles t JOIN employees e ON e.id=t.employee_id WHERE t.id=$1 AND t.archived_at IS NULL AND t.faculty_status<>'inactive' AND e.archived_at IS NULL AND e.employment_status IN('active','on_leave') FOR UPDATE OF e`;if(kind==='guardian')query=`SELECT g.id,g.user_id,g.guardian_number identifier,g.email,concat_ws(' ',g.first_name,g.middle_name,g.last_name) display_name FROM guardians g WHERE g.id=$1 AND g.archived_at IS NULL AND EXISTS(SELECT 1 FROM student_guardians sg JOIN students s ON s.id=sg.student_id WHERE sg.guardian_id=g.id AND sg.archived_at IS NULL AND sg.receives_communications AND s.archived_at IS NULL AND s.enrollment_status='enrolled') FOR UPDATE`;const found=await client.query(query,[personId]);const person=found.rows[0];if(!person)throw new AppError(400,'PORTAL_NOT_ELIGIBLE',`This ${kind} is not currently eligible for portal activation`);let userId=person.user_id?String(person.user_id):'';let temporaryPassword:string|undefined;let created=false;if(!userId){temporaryPassword=createTemporaryPassword();const result=await client.query(`INSERT INTO users(email,display_name,password_hash,account_type,must_change_password) VALUES($1,$2,$3,$4,true) RETURNING id`,[person.email?String(person.email).toLowerCase():null,person.display_name,await hashPassword(temporaryPassword),accountFor[kind]]);userId=String(result.rows[0].id);const table=kind==='student'?'students':kind==='teacher'?'employees':'guardians';await client.query(`UPDATE ${table} SET user_id=$2,updated_at=now(),version=version+1 WHERE id=$1`,[person.id,userId]);created=true;}else{await client.query(`INSERT INTO login_identities(user_id,type,normalized_value,is_primary) VALUES($1,$2,$3,true) ON CONFLICT(type,user_id) DO UPDATE SET normalized_value=excluded.normalized_value,active=true,updated_at=now()`,[userId,aliasFor[kind],String(person.identifier).trim().toLowerCase()]);}
 const portalRole=await roleId(client,roleFor[kind]);await client.query('INSERT INTO user_roles(user_id,role_id,assigned_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[userId,portalRole,ctx.actorId]);await client.query("UPDATE users SET status='active',account_type=$2,updated_at=now(),version=version+1 WHERE id=$1",[userId,accountFor[kind]]);await securityRepository.audit({actorUserId:ctx.actorId,action:`security.portal.${kind}.activate`,targetType:'user',targetId:userId,outcome:'success',requestId:ctx.requestId,ipAddress:ctx.ip,metadata:{personId,created,mustChangePassword:created}},client);await client.query('COMMIT');return{userId,displayName:String(person.display_name),loginIdentifier:String(person.identifier),...(temporaryPassword?{temporaryPassword}:{}),created,status:created?'created':'already_active'};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}

 async activateStudents(studentIds:string[],ctx:Context){const created:Result[]=[];let skipped=0;const failed:{studentId:string;reason:string}[]=[];for(const studentId of [...new Set(studentIds)]){try{const result=await this.activate('student',studentId,ctx);if(result.created)created.push(result);else skipped++;}catch(error){failed.push({studentId,reason:error instanceof AppError?error.code:'ACTIVATION_FAILED'});}}return{created,skipped,failed,count:{created:created.length,skipped,failed:failed.length}};}

 async adminChangePassword(userId:string,passwordHash:string,requireChange:boolean,ctx:Context){const client=await pool.connect();try{await client.query('BEGIN');const result=await client.query(`UPDATE users SET password_hash=$2,must_change_password=$3,password_changed_at=now(),failed_login_count=0,locked_until=NULL,updated_at=now(),version=version+1 WHERE id=$1 AND archived_at IS NULL`,[userId,passwordHash,requireChange]);if(!result.rowCount)throw new AppError(404,'USER_NOT_FOUND','User was not found');const revoked=await client.query('UPDATE auth_sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE user_id=$1 AND revoked_at IS NULL',[userId]);await securityRepository.audit({actorUserId:ctx.actorId,action:'security.user.password_admin_change',targetType:'user',targetId:userId,outcome:'success',requestId:ctx.requestId,ipAddress:ctx.ip,metadata:{mustChangePassword:requireChange,sessionsRevoked:revoked.rowCount??0}},client);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
}
export const provisioningService=new ProvisioningService();
