CREATE TABLE computer_lab_equipment(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),equipment_code varchar(60) NOT NULL UNIQUE,asset_number varchar(100),equipment_type varchar(30) NOT NULL CHECK(equipment_type IN('laptop','monitor','keyboard','mouse','headset','webcam','ups','printer','projector','network_switch','router','access_point','adapter','cable','other')),manufacturer varchar(160),model varchar(160),serial_number varchar(160),
 laboratory_id uuid REFERENCES computer_laboratories(id) ON DELETE RESTRICT,workstation_id uuid REFERENCES computer_lab_workstations(id) ON DELETE RESTRICT,assignment_status varchar(30) NOT NULL CHECK(assignment_status IN('assigned_to_workstation','assigned_to_lab','in_storage','unassigned','maintenance','retired','lost')),condition_status varchar(30) NOT NULL DEFAULT'good' CHECK(condition_status IN('good','fair','damaged','non_functional')),
 purchase_date date,warranty_expiration_date date,notes text,created_by_user_id uuid NOT NULL REFERENCES users(id),updated_by_user_id uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),archived_at timestamptz,
 CHECK((assignment_status='assigned_to_workstation'AND laboratory_id IS NOT NULL AND workstation_id IS NOT NULL)OR(assignment_status='assigned_to_lab'AND laboratory_id IS NOT NULL AND workstation_id IS NULL)OR(assignment_status IN('in_storage','unassigned','maintenance')AND workstation_id IS NULL)OR(assignment_status IN('retired','lost')AND laboratory_id IS NULL AND workstation_id IS NULL)),CHECK(equipment_type<>'other'OR length(trim(notes))>=5),CHECK(warranty_expiration_date IS NULL OR purchase_date IS NULL OR warranty_expiration_date>=purchase_date)
);
CREATE UNIQUE INDEX computer_lab_equipment_asset_unique ON computer_lab_equipment(lower(asset_number))WHERE asset_number IS NOT NULL AND archived_at IS NULL;
CREATE UNIQUE INDEX computer_lab_equipment_serial_unique ON computer_lab_equipment(lower(serial_number))WHERE serial_number IS NOT NULL AND archived_at IS NULL;
CREATE INDEX computer_lab_equipment_listing_idx ON computer_lab_equipment(archived_at,assignment_status,condition_status,equipment_type,laboratory_id);
CREATE TABLE computer_lab_equipment_transfers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),equipment_id uuid NOT NULL REFERENCES computer_lab_equipment(id)ON DELETE RESTRICT,from_laboratory_id uuid REFERENCES computer_laboratories(id),from_workstation_id uuid REFERENCES computer_lab_workstations(id),from_assignment_status varchar(30),to_laboratory_id uuid REFERENCES computer_laboratories(id),to_workstation_id uuid REFERENCES computer_lab_workstations(id),to_assignment_status varchar(30)NOT NULL,transferred_by_user_id uuid NOT NULL REFERENCES users(id),reason text,transferred_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX computer_lab_equipment_transfer_history_idx ON computer_lab_equipment_transfers(equipment_id,transferred_at DESC);
INSERT INTO permissions(code,description)VALUES('computer_lab.equipment.view','View Computer Laboratory equipment and transfer history'),('computer_lab.equipment.manage','Manage and transfer Computer Laboratory equipment')ON CONFLICT(code)DO UPDATE SET description=EXCLUDED.description;
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code IN('super_administrator','computer_lab_administrator')AND p.code LIKE'computer_lab.equipment.%'ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='computer_lab_staff'AND p.code='computer_lab.equipment.view'ON CONFLICT DO NOTHING;
