CREATE TABLE computer_lab_software(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name varchar(180) NOT NULL,vendor varchar(180),software_category varchar(40) NOT NULL CHECK(software_category IN('operating_system','office_productivity','browser','programming','database','graphics_design','engineering','education','communication','security','utility','other')),default_version varchar(100),license_type varchar(30) NOT NULL CHECK(license_type IN('free','open_source','school_license','site_license','volume_license','subscription','per_device','per_user','trial','unknown')),license_count integer CHECK(license_count IS NULL OR license_count>0),license_expiration_date date,license_reference varchar(240),website_or_reference varchar(500),notes text,status varchar(20) NOT NULL DEFAULT'active'CHECK(status IN('active','inactive','retired')),created_by_user_id uuid NOT NULL REFERENCES users(id),updated_by_user_id uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),archived_at timestamptz
);
CREATE UNIQUE INDEX computer_lab_software_name_vendor_unique ON computer_lab_software(lower(name),lower(COALESCE(vendor,'')))WHERE archived_at IS NULL;
CREATE INDEX computer_lab_software_listing_idx ON computer_lab_software(archived_at,status,software_category,license_type,name);
CREATE TABLE computer_lab_workstation_software(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workstation_id uuid NOT NULL REFERENCES computer_lab_workstations(id)ON DELETE RESTRICT,software_id uuid NOT NULL REFERENCES computer_lab_software(id)ON DELETE RESTRICT,expected_version varchar(100),configuration_status varchar(30) NOT NULL DEFAULT'expected'CHECK(configuration_status IN('expected','installed','needs_update','missing','not_applicable')),assigned_at timestamptz NOT NULL DEFAULT now(),notes text,created_by_user_id uuid NOT NULL REFERENCES users(id),updated_by_user_id uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),archived_at timestamptz
);
CREATE UNIQUE INDEX computer_lab_workstation_software_active_unique ON computer_lab_workstation_software(workstation_id,software_id)WHERE archived_at IS NULL;
CREATE INDEX computer_lab_workstation_software_workstation_idx ON computer_lab_workstation_software(workstation_id,archived_at,configuration_status);
CREATE INDEX computer_lab_workstation_software_software_idx ON computer_lab_workstation_software(software_id,archived_at,configuration_status);
INSERT INTO permissions(code,description)VALUES('computer_lab.software.view','View Computer Laboratory software and configuration records'),('computer_lab.software.manage','Manage Computer Laboratory software and workstation configuration records')ON CONFLICT(code)DO UPDATE SET description=EXCLUDED.description;
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code IN('super_administrator','computer_lab_administrator')AND p.code LIKE'computer_lab.software.%'ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='computer_lab_staff'AND p.code='computer_lab.software.view'ON CONFLICT DO NOTHING;
