-- Durable Phase 21 RBAC reconciliation for upgraded installations.
INSERT INTO permissions(code,description) VALUES
('computer_lab.access','Access Computer Laboratory operations'),('computer_lab.dashboard.view','View the Computer Laboratory dashboard'),('computer_lab.labs.view','View laboratories'),('computer_lab.labs.manage','Manage laboratories'),('computer_lab.workstations.view','View workstations'),('computer_lab.workstations.manage','Manage workstations'),('computer_lab.schedule.view','View laboratory schedules'),('computer_lab.schedule.manage','Manage laboratory schedules'),('computer_lab.sessions.view','View laboratory sessions'),('computer_lab.sessions.manage','Manage laboratory sessions'),('computer_lab.sessions.override','Override laboratory session restrictions'),('computer_lab.issues.view','View laboratory issues'),('computer_lab.issues.manage','Manage laboratory issues'),('computer_lab.maintenance.view','View laboratory maintenance'),('computer_lab.maintenance.manage','Manage laboratory maintenance'),('computer_lab.equipment.view','View laboratory equipment'),('computer_lab.equipment.manage','Manage laboratory equipment'),('computer_lab.software.view','View laboratory software'),('computer_lab.software.manage','Manage laboratory software'),('computer_lab.reports.view','View Computer Laboratory reports'),('computer_lab.settings.manage','Manage Computer Laboratory settings')
ON CONFLICT(code) DO UPDATE SET description=EXCLUDED.description;

INSERT INTO roles(code,name,description,is_system) VALUES
('computer_lab_administrator','Computer Laboratory Administrator','Built-in Computer Laboratory Administrator role',true),
('computer_lab_staff','Computer Laboratory Staff','Built-in Computer Laboratory Staff role',true)
ON CONFLICT(code) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description;

INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code IN('super_administrator','school_administrator','computer_lab_administrator') AND p.code LIKE 'computer_lab.%' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='computer_lab_staff' AND p.code IN('computer_lab.access','computer_lab.dashboard.view','computer_lab.labs.view','computer_lab.workstations.view','computer_lab.schedule.view','computer_lab.sessions.view','computer_lab.sessions.manage','computer_lab.issues.view','computer_lab.issues.manage','computer_lab.maintenance.view','computer_lab.maintenance.manage','computer_lab.equipment.view','computer_lab.equipment.manage','computer_lab.software.view','computer_lab.reports.view') ON CONFLICT DO NOTHING;
