import { z } from 'zod';

const uuid = z.string().uuid();
const text = (max = 160) => z.string().trim().min(1).max(max);
const optionalText = (max = 500) => z.string().trim().max(max).nullable().optional();
const code = text(80);
const date = z.iso.date();
const dateTime = z.iso.datetime({ offset: true });

export const resourceDefinitions = {
  schools: { table: 'schools', permission: 'academic.config', fields: { code: 'code', name: 'name', legalName: 'legal_name', email: 'email', phone: 'phone', addressLine: 'address_line', city: 'city', province: 'province', countryCode: 'country_code', active: 'active' }, schema: z.object({ code: text(40).regex(/^[A-Z][A-Z0-9_-]*$/), name: text(), legalName: optionalText(), email: z.email().nullable().optional(), phone: optionalText(50), addressLine: optionalText(), city: optionalText(100), province: optionalText(100), countryCode: z.string().length(2).toUpperCase().default('PH'), active: z.boolean().default(true) }).strict() },
  campuses: { table: 'campuses', permission: 'academic.config', fields: { schoolId: 'school_id', code: 'code', name: 'name', addressLine: 'address_line', city: 'city', province: 'province', phone: 'phone', active: 'active' }, schema: z.object({ schoolId: uuid, code, name: text(), addressLine: optionalText(), city: optionalText(100), province: optionalText(100), phone: optionalText(50), active: z.boolean().default(true) }).strict() },
  'school-years': { table: 'school_years', permission: 'academic.config', fields: { schoolId: 'school_id', name: 'name', startsOn: 'starts_on', endsOn: 'ends_on', status: 'status' }, schema: z.object({ schoolId: uuid, name: text(40), startsOn: date, endsOn: date, status: z.enum(['planned', 'active', 'closed']).default('planned') }).strict().refine((value) => value.endsOn > value.startsOn, { message: 'School year end must be after its start', path: ['endsOn'] }) },
  terms: { table: 'academic_terms', permission: 'academic.config', fields: { schoolYearId: 'school_year_id', code: 'code', name: 'name', sequence: 'sequence', startsOn: 'starts_on', endsOn: 'ends_on', status: 'status' }, schema: z.object({ schoolYearId: uuid, code, name: text(), sequence: z.number().int().positive(), startsOn: date, endsOn: date, status: z.enum(['planned', 'active', 'closed']).default('planned') }).strict().refine((value) => value.endsOn >= value.startsOn, { message: 'Term end must not precede its start', path: ['endsOn'] }) },
  'grading-periods': { table: 'grading_periods', permission: 'academic.config', fields: { schoolYearId: 'school_year_id', academicTermId: 'academic_term_id', code: 'code', name: 'name', sequence: 'sequence', startsOn: 'starts_on', endsOn: 'ends_on', status: 'status', weight: 'weight' }, schema: z.object({ schoolYearId: uuid, academicTermId: uuid.nullable().optional(), code: text(40), name: text(120), sequence: z.number().int().positive(), startsOn: date, endsOn: date, status: z.enum(['planned','open','closed']).default('planned'), weight: z.number().positive().default(1) }).strict().refine((value)=>value.endsOn>=value.startsOn,{message:'Grading period end must not precede its start',path:['endsOn']}) },
  departments: { table: 'departments', permission: 'academic.config', fields: { schoolId: 'school_id', campusId: 'campus_id', code: 'code', name: 'name', category: 'category', active: 'active' }, schema: z.object({ schoolId: uuid, campusId: uuid.nullable().optional(), code, name: text(), category: z.enum(['academic', 'administrative', 'support']).default('academic'), active: z.boolean().default(true) }).strict() },
  'grade-levels': { table: 'grade_levels', permission: 'academic.config', fields: { schoolId: 'school_id', code: 'code', name: 'name', sequence: 'sequence', educationStage: 'education_stage', active: 'active' }, schema: z.object({ schoolId: uuid, code, name: text(), sequence: z.number().int().positive(), educationStage: text(80), active: z.boolean().default(true) }).strict() },
  subjects: { table: 'subjects', permission: 'academic.config', fields: { schoolId: 'school_id', departmentId: 'department_id', code: 'code', name: 'name', description: 'description', active: 'active' }, schema: z.object({ schoolId: uuid, departmentId: uuid.nullable().optional(), code, name: text(), description: optionalText(1000), active: z.boolean().default(true) }).strict() },
  classrooms: { table: 'classrooms', permission: 'academic.config', fields: { campusId: 'campus_id', code: 'code', name: 'name', building: 'building', floor: 'floor', capacity: 'capacity', active: 'active' }, schema: z.object({ campusId: uuid, code, name: text(), building: optionalText(100), floor: optionalText(40), capacity: z.number().int().positive().nullable().optional(), active: z.boolean().default(true) }).strict() },
  sections: { table: 'sections', permission: 'academic.config', fields: { schoolYearId: 'school_year_id', gradeLevelId: 'grade_level_id', campusId: 'campus_id', code: 'code', name: 'name', capacity: 'capacity', active: 'active' }, schema: z.object({ schoolYearId: uuid, gradeLevelId: uuid, campusId: uuid, code, name: text(), capacity: z.number().int().positive().nullable().optional(), active: z.boolean().default(true) }).strict() },
  statuses: { table: 'academic_statuses', permission: 'academic.config', fields: { schoolId: 'school_id', entityType: 'entity_type', code: 'code', label: 'label', displayOrder: 'display_order', isTerminal: 'is_terminal', active: 'active' }, schema: z.object({ schoolId: uuid, entityType: z.enum(['student', 'enrollment', 'term', 'section']), code, label: text(), displayOrder: z.number().int().positive().default(1), isTerminal: z.boolean().default(false), active: z.boolean().default(true) }).strict() },
  events: { table: 'calendar_events', permission: 'academic.calendar', fields: { schoolId: 'school_id', campusId: 'campus_id', schoolYearId: 'school_year_id', academicTermId: 'academic_term_id', title: 'title', eventType: 'event_type', startsAt: 'starts_at', endsAt: 'ends_at', allDay: 'all_day', location: 'location', description: 'description', status: 'status' }, schema: z.object({ schoolId: uuid, campusId: uuid.nullable().optional(), schoolYearId: uuid.nullable().optional(), academicTermId: uuid.nullable().optional(), title: text(200), eventType: z.enum(['academic', 'holiday', 'administrative', 'community', 'other']), startsAt: dateTime, endsAt: dateTime, allDay: z.boolean().default(false), location: optionalText(200), description: optionalText(2000), status: z.enum(['planned', 'published', 'cancelled']).default('planned') }).strict().refine((value) => value.endsAt >= value.startsAt, { message: 'Event end must not precede its start', path: ['endsAt'] }) },
} as const;

export type ResourceName = keyof typeof resourceDefinitions;
export const isResourceName = (value: string): value is ResourceName => Object.hasOwn(resourceDefinitions, value);
