import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { AdmissionDocumentPicker, type PendingAdmissionDocument } from './AdmissionDocumentPicker';

describe('AdmissionDocumentPicker',()=>{
  afterEach(()=>cleanup());
  it('keeps multiple files under the selected document type and removes one independently',()=>{let selected:PendingAdmissionDocument[]=[];const onChange=vi.fn((value:PendingAdmissionDocument[])=>{selected=value;rerender(<AdmissionDocumentPicker value={selected} onChange={onChange}/>)});const{rerender}=render(<AdmissionDocumentPicker value={selected} onChange={onChange}/>);const input=screen.getByLabelText(/choose files/i);fireEvent.change(input,{target:{files:[new File(['front'],'birth-front.jpg',{type:'image/jpeg'}),new File(['back'],'birth-back.jpg',{type:'image/jpeg'})]}});expect(screen.getByText('birth-front.jpg')).toBeInTheDocument();expect(screen.getByText('birth-back.jpg')).toBeInTheDocument();expect(screen.getAllByText('Birth Certificate')).toHaveLength(2);fireEvent.click(screen.getByRole('button',{name:'Remove birth-front.jpg'}));expect(screen.queryByText('birth-front.jpg')).not.toBeInTheDocument();expect(screen.getByText('birth-back.jpg')).toBeInTheDocument();});
  it('preserves separate type tags while files share one pending list',()=>{let selected:PendingAdmissionDocument[]=[];const onChange=vi.fn((value:PendingAdmissionDocument[])=>{selected=value;rerender(<AdmissionDocumentPicker value={selected} onChange={onChange}/>)});const{rerender}=render(<AdmissionDocumentPicker value={selected} onChange={onChange}/>);const input=screen.getByLabelText(/choose files/i);fireEvent.change(input,{target:{files:[new File(['birth'],'birth.jpg',{type:'image/jpeg'})]}});fireEvent.change(screen.getByLabelText(/document type/i),{target:{value:'report_card'}});fireEvent.change(input,{target:{files:[new File(['card'],'card.pdf',{type:'application/pdf'})]}});expect(selected.map(item=>item.documentType)).toEqual(['birth_certificate','report_card']);expect(screen.getAllByText('Birth Certificate')).toHaveLength(2);expect(screen.getAllByText('Report Card')).toHaveLength(2);});
});
