import{GraduationCap,LogOut,Menu,UserRound,X}from'lucide-react';
import{useEffect,useRef,useState,type ReactNode}from'react';
import{Link,Outlet}from'react-router-dom';
import{useAuth}from'../auth/AuthContext';
import{AdministrationNav}from'./AdministrationNav';
import{ExperienceSwitcher}from'./ExperienceSwitcher';
import{NotificationBell}from'./NotificationBell';

export function AppShell({children}:{children?:ReactNode}){
  const[open,setOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false);const{user,logout,has}=useAuth();const close=()=>setOpen(false);const accountRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!accountOpen)return;const closeMenu=(event:MouseEvent)=>{if(!accountRef.current?.contains(event.target as Node))setAccountOpen(false)};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setAccountOpen(false)};document.addEventListener('mousedown',closeMenu);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('mousedown',closeMenu);document.removeEventListener('keydown',escape)}},[accountOpen]);
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to main content</a><aside className={`sidebar ${open?'sidebar--open':''}`} aria-label="Administration navigation"><div className="brand"><img src="/mmsc-logo.jpg" alt="MMSC crest"/><div><strong>MMSC</strong><span>Administration</span></div></div><button className="close-nav" onClick={close} aria-label="Close navigation"><X/></button><AdministrationNav has={has} onNavigate={close}/><div className="sidebar-note"><GraduationCap/><span>One school.<br/>One connected platform.</span></div></aside>{open&&<button className="backdrop" aria-label="Close navigation" onClick={close}/>}<div className="main-column"><header className="topbar"><button className="menu" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button><div><span className="eyebrow">My Messiah School of Cavite</span><strong>{user?.displayName}</strong></div><ExperienceSwitcher/>{has('notification.inbox.access')&&<NotificationBell to="/notifications" className="icon-button notification-bell"/>}<div className="account-menu" ref={accountRef}><button className="avatar" aria-haspopup="menu" aria-expanded={accountOpen} aria-label={`Open account menu for ${user?.displayName}`} title={user?.email} onClick={()=>setAccountOpen(value=>!value)}>{user?.displayName.charAt(0).toUpperCase()}</button>{accountOpen&&<div className="account-popover" role="menu"><div><strong>{user?.displayName}</strong><small>{user?.loginIdentifier??user?.email}</small></div><Link role="menuitem" to="/account" onClick={()=>setAccountOpen(false)}><UserRound/>My Account</Link><button role="menuitem" onClick={()=>void logout()}><LogOut/>Sign Out</button></div>}</div></header><main id="main-content" data-route-main tabIndex={-1}>{children??<Outlet/>}</main></div></div>;
}
