import { KeyRound, Plus, RefreshCw, ShieldX } from 'lucide-react';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api, apiErrorMessage } from '../lib/api';
import { EmptyState, Modal } from './ui';

type Credential={id:string;credentialType:'rfid'|'qr';displaySuffix:string;status:string;issuedAt:string;expiresAt?:string|null;lastUsedAt?:string|null;version:number};
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());
const when=(value?:string|null)=>value?new Date(value).toLocaleString('en-PH'):'—';
const minimumExpiration=()=>{const date=new Date(Date.now()+60_000),offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};

export function CredentialsPanel({ownerType,ownerId,canManage=true}:{ownerType:'student'|'employee';ownerId:string;canManage?:boolean}){
 const[items,setItems]=useState<Credential[]>([]),[registering,setRegistering]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[issuedValue,setIssuedValue]=useState(''),[replace,setReplace]=useState<Credential>();
 const load=useCallback(async()=>{try{setItems((await api<{items:Credential[]}>(`/credentials?ownerType=${ownerType}&ownerId=${ownerId}`)).items);setError('')}catch(cause){setError(apiErrorMessage(cause,'Unable to load credentials'))}},[ownerId,ownerType]);
 useEffect(()=>{void load()},[load]);
 const register=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),type=String(form.get('credentialType')),generate=form.get('generate')==='on';setSaving(true);setError('');try{const response=await api<{issuedValue?:string}>('/credentials',{method:'POST',body:JSON.stringify({ownerType,ownerId,credentialType:type,credentialValue:String(form.get('credentialValue')).trim()||undefined,generate,expiresAt:String(form.get('expiresAt')).trim()?new Date(String(form.get('expiresAt'))).toISOString():null})});setIssuedValue(response.issuedValue??'');setRegistering(false);await load()}catch(cause){setError(apiErrorMessage(cause,'Unable to register credential'))}finally{setSaving(false)}};
 const transition=async(item:Credential,status:string,replacementValue?:string)=>{setSaving(true);setError('');setNotice('');try{const response=await api<{issuedValue?:string}>(`/credentials/${item.id}/status`,{method:'POST',body:JSON.stringify({status,version:item.version,replacementValue:replacementValue||undefined})});if(response.issuedValue)setIssuedValue(response.issuedValue);setReplace(undefined);setNotice(status==='replaced'?'Credential replaced successfully.':`Credential marked ${label(status)}.`)}catch(cause){setError(apiErrorMessage(cause,'Unable to update credential'));setSaving(false);return}setSaving(false);await load()};
 return <section className="credentials-panel">
  <header><div><h4><KeyRound/>Machine-readable credentials</h4><p>RFID and QR credentials resolve only to this authoritative {ownerType} identity.</p></div>{canManage&&<button type="button" className="button" onClick={()=>setRegistering(true)}><Plus/>Register Credential</button>}</header>
  {error&&<div className="form-error" role="alert">{error}</div>}{notice&&<div className="form-success" role="status">{notice}</div>}
  {issuedValue&&<div className="credential-issued" role="status"><strong>Copy this generated QR value now</strong><code>{issuedValue}</code><p>It will not be shown again. Encode only this opaque value in the QR code.</p><button type="button" className="text-button" onClick={()=>setIssuedValue('')}>Dismiss</button></div>}
  {items.length?<div className="table-wrap credential-table"><table><thead><tr><th>Type</th><th>Credential ID</th><th>Status</th><th>Issued</th><th>Expiration</th><th>Last used</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.credentialType.toUpperCase()}</td><td><code>••••••{item.displaySuffix}</code></td><td><span className={`status-pill ${item.status}`}>{label(item.status)}</span></td><td>{when(item.issuedAt)}</td><td>{when(item.expiresAt)}</td><td>{when(item.lastUsedAt)}</td><td><div className="table-actions">{canManage&&['inactive','lost'].includes(item.status)&&<button type="button" className="text-button" onClick={()=>void transition(item,'active')}>Activate</button>}{canManage&&item.status==='active'&&<><button type="button" className="text-button" onClick={()=>void transition(item,'inactive')}>Deactivate</button><button type="button" className="text-button" onClick={()=>void transition(item,'lost')}>Mark Lost</button></>}{canManage&&['active','lost'].includes(item.status)&&<button type="button" className="text-button" onClick={()=>setReplace(item)}><RefreshCw/>Replace</button>}{canManage&&['active','inactive','lost'].includes(item.status)&&<button type="button" className="text-button danger" onClick={()=>void transition(item,'revoked')}><ShieldX/>Revoke</button>}</div></td></tr>)}</tbody></table></div>:<EmptyState title="No credentials registered" message="Register an RFID card or QR credential for attendance and future shared MMSC services."/>}
  <Modal open={registering} title="Register Credential" description={`Assign an RFID or QR credential to this ${ownerType}.`} error={error} busy={saving} onClose={()=>setRegistering(false)} footer={<><button type="button" className="text-button" onClick={()=>setRegistering(false)}>Cancel</button><button type="submit" form="credential-registration" className="button">Register</button></>}><form id="credential-registration" className="modal-form" onSubmit={register}><label>Credential type<select name="credentialType" defaultValue="rfid"><option value="rfid">RFID</option><option value="qr">QR Code</option></select></label><label>Credential value<input name="credentialValue" autoFocus autoComplete="off" placeholder="Enter or scan value"/></label><label>Expiration (optional)<input name="expiresAt" type="datetime-local" min={minimumExpiration()}/><small>Leave blank when the credential should not expire.</small></label><label className="check-row"><input name="generate" type="checkbox"/>Generate secure QR value</label></form></Modal>
  <Modal open={Boolean(replace)} title="Replace Credential" description={replace?.credentialType==='rfid'?'Scan or enter the replacement RFID card.':'Enter a value or leave blank to generate a new secure QR value.'} error={error} busy={saving} onClose={()=>setReplace(undefined)} footer={<><button type="button" className="text-button" onClick={()=>setReplace(undefined)}>Cancel</button><button type="submit" form="credential-replacement" className="button">Replace</button></>}><form id="credential-replacement" className="modal-form" onSubmit={event=>{event.preventDefault();if(replace)void transition(replace,'replaced',String(new FormData(event.currentTarget).get('replacementValue')).trim())}}><label>Replacement value<input name="replacementValue" autoFocus autoComplete="off" required={replace?.credentialType==='rfid'} placeholder="Scan replacement credential"/></label></form></Modal>
 </section>
}
