import express from 'express';
import request from 'supertest';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { admissionsRepository } from '../admissions/repository.js';
import { AppError, errorHandler } from '../lib/errors.js';
import { requestContext } from '../middleware/request-context.js';
import { admissionsRouter } from './admissions.js';

const userId='08f35c64-1fd8-4c59-abd9-03466935c97b';
const applicationId='18f35c64-1fd8-4c59-abd9-03466935c97b';
function app(permissions:string[]){const instance=express();instance.use(express.json());instance.use(requestContext);instance.use((req,_res,next)=>{req.auth={userId,authenticated:true,sessionId:'session',email:'registrar@mmsc.test',displayName:'Registrar',roles:['registrar'],permissions};next();});instance.use('/api/v1',admissionsRouter);instance.use(errorHandler);return instance;}
afterEach(()=>vi.restoreAllMocks());
describe('Phase 15 admissions routes',()=>{
  it('protects the application queue',async()=>{const response=await request(app([])).get('/api/v1/admissions');expect(response.status).toBe(403);});
  it('passes queue filters, sorting, and pagination through the protected boundary',async()=>{const list=vi.spyOn(admissionsRepository,'list').mockResolvedValue({items:[],total:0});const response=await request(app(['admission.view'])).get(`/api/v1/admissions?status=pending&applicationType=returning_student&gradeLevelId=${userId}&schoolYearId=${applicationId}&sort=submitted_asc&limit=25&offset=25`);expect(response.status).toBe(200);expect(list).toHaveBeenCalledWith({status:'pending',applicationType:'returning_student',gradeLevelId:userId,schoolYearId:applicationId,sort:'submitted_asc',limit:25,offset:25});});
  it('validates registration input',async()=>{const response=await request(app(['admission.manage'])).post('/api/v1/admissions').send({applicationType:'new_student'});expect(response.status).toBe(400);});
  it('requires a returning application to match an existing Student',async()=>{const response=await request(app(['admission.manage'])).post('/api/v1/admissions').send({schoolId:userId,applicationType:'returning_student',schoolYearId:userId,gradeLevelId:userId,firstName:'Ana',lastName:'Reyes',birthDate:'2015-01-01',guardian:{firstName:'Maria',lastName:'Reyes',relationshipType:'mother',mobilePhone:'09170000000'}});expect(response.status).toBe(400);});
  it('hands approved applications to the Enrollment queue instead of creating Students early',async()=>{const convert=vi.spyOn(admissionsRepository,'convert');const response=await request(app(['admission.convert'])).post(`/api/v1/admissions/${applicationId}/convert`).send({version:1});expect(response.status).toBe(409);expect(response.body.error.code).toBe('ENROLLMENT_HANDOFF_REQUIRED');expect(convert).not.toHaveBeenCalled();});
  it('protects registration activation with Admissions management permission',async()=>{const response=await request(app(['admission.view'])).put('/api/v1/admissions/registration-configuration').send({schoolYearId:applicationId,isEnabled:true});expect(response.status).toBe(403);});
  it('updates the single registration configuration through the protected boundary',async()=>{const configure=vi.spyOn(admissionsRepository,'setRegistrationConfiguration').mockResolvedValue({schoolYears:[],active:null});const response=await request(app(['admission.manage'])).put('/api/v1/admissions/registration-configuration').send({schoolYearId:applicationId,isEnabled:true});expect(response.status).toBe(200);expect(configure).toHaveBeenCalledWith(applicationId,true,expect.objectContaining({actorId:userId}));});
  it('requires review permission to edit an application',async()=>{const response=await request(app(['admission.view'])).put(`/api/v1/admissions/${applicationId}`).send({});expect(response.status).toBe(403);});
  it('uploads an optional staff document through the shared Admission document route',async()=>{const upload=vi.spyOn(admissionsRepository,'uploadDocument').mockResolvedValue({id:'document'});const response=await request(app(['admission.review'])).post(`/api/v1/admissions/${applicationId}/documents`).field('documentType','report_card').attach('document',Buffer.from('%PDF-test'),'report-card.pdf');expect(response.status).toBe(201);expect(upload).toHaveBeenCalledWith(applicationId,expect.objectContaining({mimetype:'application/pdf'}),'report_card',expect.objectContaining({actorId:userId}));});
  it('returns a meaningful error when a staff upload has no file',async()=>{const response=await request(app(['admission.review'])).post(`/api/v1/admissions/${applicationId}/documents`).field('documentType','report_card');expect(response.status).toBe(400);expect(response.body.error.code).toBe('DOCUMENT_REQUIRED');});
  it('downloads an Admission-owned document for an authorized user',async()=>{vi.spyOn(admissionsRepository,'readDocument').mockResolvedValue({data:Buffer.from('%PDF-test'),filename:'report-card.pdf',mimeType:'application/pdf'});const response=await request(app(['admission.view'])).get(`/api/v1/admissions/${applicationId}/documents/${userId}`);expect(response.status).toBe(200);expect(response.headers['content-type']).toContain('application/pdf');expect(response.headers['content-disposition']).toContain('report-card.pdf');expect(admissionsRepository.readDocument).toHaveBeenCalledWith(applicationId,userId);});
  it('denies document download without Admissions view permission',async()=>{const read=vi.spyOn(admissionsRepository,'readDocument');const response=await request(app([])).get(`/api/v1/admissions/${applicationId}/documents/${userId}`);expect(response.status).toBe(403);expect(read).not.toHaveBeenCalled();});
  it('does not return a document owned by another application',async()=>{vi.spyOn(admissionsRepository,'readDocument').mockRejectedValue(new AppError(404,'DOCUMENT_NOT_FOUND','Document was not found'));const response=await request(app(['admission.view'])).get(`/api/v1/admissions/${applicationId}/documents/${userId}`);expect(response.status).toBe(404);expect(response.body.error.code).toBe('DOCUMENT_NOT_FOUND');});
});
