import{Router,type Request}from'express';import{z}from'zod';import{assignmentRepository}from'../assignments/repository.js';import{copySchema,curriculumBulkSchema,curriculumSchema,curriculumUpdateSchema,teachingBulkSchema,teachingSchema,teachingUpdateSchema}from'../assignments/schemas.js';import{AppError}from'../lib/errors.js';import{requirePermission}from'../security/middleware.js';
export const assignmentsRouter=Router();const uuid=z.string().uuid(),version=z.coerce.number().int().positive();const ctx=(r:Request)=>({actorId:r.auth.userId!,requestId:String(r.id),ip:r.ip?.replace(/^::ffff:/,'')});
assignmentsRouter.get('/assignments/context',requirePermission('academic.assignment.view'),async(_r,res,n)=>{try{res.json(await assignmentRepository.context());}catch(e){n(e);}});
assignmentsRouter.get('/assignments',requirePermission('academic.assignment.view'),async(r,res,n)=>{try{const q=z.object({schoolYearId:z.preprocess(v=>v===''?undefined:v,uuid.optional())}).parse(r.query);const[curriculum,teaching]=await Promise.all([assignmentRepository.listCurriculum(q.schoolYearId),assignmentRepository.listTeaching(q.schoolYearId)]);res.json({curriculum,teaching});}catch(e){n(e);}});
assignmentsRouter.get('/assignments/workspace',requirePermission('academic.assignment.view'),async(r,res,n)=>{try{const q=z.object({schoolYearId:uuid}).parse(r.query);res.json(await assignmentRepository.workspace(q.schoolYearId));}catch(e){n(e);}});
assignmentsRouter.get('/assignments/curriculum/grade-level/:gradeLevelId',requirePermission('academic.assignment.view'),async(r,res,n)=>{try{const q=z.object({schoolYearId:uuid}).parse(r.query);res.json(await assignmentRepository.gradeCurriculum(q.schoolYearId,uuid.parse(r.params.gradeLevelId)));}catch(e){n(e);}});
assignmentsRouter.put('/assignments/curriculum/grade-level/:gradeLevelId',requirePermission('academic.assignment.manage'),async(r,res,n)=>{try{res.json(await assignmentRepository.saveGradeCurriculum(curriculumBulkSchema.parse({...r.body,gradeLevelId:r.params.gradeLevelId}),ctx(r)));}catch(e){n(e);}});
assignmentsRouter.get('/assignments/teaching/section/:sectionId',requirePermission('academic.assignment.view'),async(r,res,n)=>{try{const q=z.object({schoolYearId:uuid}).parse(r.query);res.json(await assignmentRepository.sectionTeaching(q.schoolYearId,uuid.parse(r.params.sectionId)));}catch(e){n(e);}});
assignmentsRouter.put('/assignments/teaching/section/:sectionId',requirePermission('academic.assignment.manage'),async(r,res,n)=>{try{res.json(await assignmentRepository.saveSectionTeaching(uuid.parse(r.params.sectionId),teachingBulkSchema.parse(r.body),ctx(r)));}catch(e){n(e);}});
for(const kind of ['curriculum','teaching']as const){assignmentsRouter.post(`/assignments/copy/${kind}/preview`,requirePermission('academic.assignment.manage'),async(r,res,n)=>{try{res.json(await assignmentRepository.copyPreview(kind,copySchema.parse(r.body)));}catch(e){n(e);}});assignmentsRouter.post(`/assignments/copy/${kind}`,requirePermission('academic.assignment.manage'),async(r,res,n)=>{try{const body=copySchema.parse(r.body);if(body.confirm!=='COPY_MISSING')throw new AppError(400,'COPY_CONFIRMATION_REQUIRED','Preview and confirm the copy before continuing');res.json(await assignmentRepository.copyMissing(kind,body,ctx(r)));}catch(e){n(e);}})}
assignmentsRouter.post('/assignments/curriculum',requirePermission('academic.assignment.manage'),async(r,res,n)=>{try{res.status(201).json({item:await assignmentRepository.createCurriculum(curriculumSchema.parse(r.body),ctx(r))});}catch(e){n(e);}});
assignmentsRouter.post('/assignments/teaching',requirePermission('academic.assignment.manage'),async(r,res,n)=>{try{res.status(201).json({item:await assignmentRepository.createTeaching(teachingSchema.parse(r.body),ctx(r))});}catch(e){n(e);}});
assignmentsRouter.get('/assignments/curriculum/:id',requirePermission('academic.assignment.view'),async(r,res,n)=>{try{const result=await assignmentRepository.curriculumDetail(uuid.parse(r.params.id));if(!result)throw new AppError(404,'CURRICULUM_ASSIGNMENT_NOT_FOUND','Curriculum assignment was not found');res.json(result);}catch(e){n(e);}});
assignmentsRouter.get('/assignments/teaching/:id',requirePermission('academic.assignment.view'),async(r,res,n)=>{try{const result=await assignmentRepository.teachingDetail(uuid.parse(r.params.id));if(!result)throw new AppError(404,'TEACHING_ASSIGNMENT_NOT_FOUND','Teaching assignment was not found');res.json(result);}catch(e){n(e);}});
assignmentsRouter.patch('/assignments/curriculum/:id',requirePermission('academic.assignment.manage'),async(r,res,n)=>{try{const body=z.object({version,data:curriculumUpdateSchema}).strict().parse(r.body);res.json({item:await assignmentRepository.updateCurriculum(uuid.parse(r.params.id),body.version,body.data,ctx(r))});}catch(e){n(e);}});
assignmentsRouter.patch('/assignments/teaching/:id',requirePermission('academic.assignment.manage'),async(r,res,n)=>{try{const body=z.object({version,data:teachingUpdateSchema}).strict().parse(r.body);res.json({item:await assignmentRepository.updateTeaching(uuid.parse(r.params.id),body.version,body.data,ctx(r))});}catch(e){n(e);}});
for(const kind of ['curriculum','teaching']as const)assignmentsRouter.delete(`/assignments/${kind}/:id`,requirePermission('academic.assignment.manage'),async(r,res,n)=>{try{if(!await assignmentRepository.archive(kind,uuid.parse(r.params.id),version.parse(r.query.version),ctx(r)))throw new AppError(409,'STALE_RECORD','The assignment changed or no longer exists');res.status(204).end();}catch(e){n(e);}});
