import express from'express';
import request from'supertest';
import{afterEach,describe,expect,it,vi}from'vitest';
import{libraryRepository}from'../library/repository.js';
import{libraryCatalogRepository}from'../library/catalog-repository.js';
import{libraryCirculationRepository}from'../library/circulation-repository.js';
import{libraryVisitorRepository}from'../library/visitor-repository.js';
import{errorHandler}from'../lib/errors.js';
import{requestContext}from'../middleware/request-context.js';
import{libraryRouter}from'./library.js';

function app(permissions:string[]){const instance=express();instance.use(express.json());instance.use(requestContext);instance.use((req,_res,next)=>{req.auth={userId:'11111111-1111-4111-8111-111111111111',authenticated:true,sessionId:'session',email:'library@mmsc.test',displayName:'Librarian',roles:['librarian'],permissions};next()});instance.use('/api/v1',libraryRouter);instance.use(errorHandler);return instance}

describe('Library portal RBAC boundary',()=>{
  afterEach(()=>vi.restoreAllMocks());
  it('denies every Library API without portal access',async()=>{const response=await request(app(['library.dashboard.view'])).get('/api/v1/library/dashboard');expect(response.status).toBe(403);expect(response.body.error.code).toBe('PERMISSION_DENIED')});
  it('allows an authorized Library dashboard and returns zero-safe metrics',async()=>{vi.spyOn(libraryRepository,'dashboard').mockResolvedValue({metrics:{totalBookCopies:0,available:0,checkedOut:0,overdue:0,visitorsToday:0,currentlyInside:0,borrowedToday:0,returnedToday:0},circulation:[],mostBorrowed:[],popularCategories:[],alerts:{lost:0,damaged:0,underRepair:0,staleVisitorSessions:0}});const response=await request(app(['library.portal.access','library.dashboard.view'])).get('/api/v1/library/dashboard');expect(response.status).toBe(200);expect(response.body.metrics.totalBookCopies).toBe(0)});
  it('requires the granular dashboard permission',async()=>{expect((await request(app(['library.portal.access'])).get('/api/v1/library/dashboard')).status).toBe(403)});
  it('separates settings viewing from management',async()=>{vi.spyOn(libraryRepository,'settings').mockResolvedValue({defaultLoanDays:14} as never);const viewer=app(['library.portal.access','library.settings.view']);expect((await request(viewer).get('/api/v1/library/settings')).status).toBe(200);expect((await request(viewer).put('/api/v1/library/settings').send({defaultLoanDays:21,maximumRenewals:2})).status).toBe(403)});
  it('validates settings before an authorized update',async()=>{const manager=app(['library.portal.access','library.settings.manage']);expect((await request(manager).put('/api/v1/library/settings').send({defaultLoanDays:0,maximumRenewals:20})).status).toBe(400)});
  it('updates the default policy and all patron overrides only with settings management',async()=>{const payload={defaultLoanDays:14,maximumRenewals:1,maximumActiveLoans:3,gracePeriodDays:1,allowBorrowingWithOverdue:false,overrides:(['student','teacher','employee']as const).map(patronType=>({patronType,enabled:patronType==='teacher',maximumActiveLoans:patronType==='teacher'?10:3,loanPeriodDays:patronType==='teacher'?30:14,maximumRenewals:1,gracePeriodDays:1,allowBorrowingWithOverdue:false}))};const update=vi.spyOn(libraryRepository,'updateSettings').mockResolvedValue(payload as never);expect((await request(app(['library.portal.access','library.settings.manage'])).put('/api/v1/library/settings').send(payload)).status).toBe(200);expect(update).toHaveBeenCalledWith(expect.objectContaining({maximumActiveLoans:3,overrides:expect.arrayContaining([expect.objectContaining({patronType:'teacher',enabled:true})])}),expect.any(Object))});
  it('supports server-paginated catalog search and filters',async()=>{const list=vi.spyOn(libraryCatalogRepository,'list').mockResolvedValue({items:[],total:0});const response=await request(app(['library.portal.access','library.catalog.view'])).get('/api/v1/library/books?search=Noli&availability=available&status=available&limit=10&offset=20');expect(response.status).toBe(200);expect(list).toHaveBeenCalledWith(expect.objectContaining({search:'Noli',availability:'available',status:'available',limit:10,offset:20}))});
  it('allows catalog managers to create and edit a book',async()=>{vi.spyOn(libraryCatalogRepository,'createBook').mockResolvedValue({id:'book',version:1});vi.spyOn(libraryCatalogRepository,'updateBook').mockResolvedValue({id:'book',version:2});const manager=app(['library.portal.access','library.catalog.manage']);expect((await request(manager).post('/api/v1/library/books').send({title:'Noli Me Tangere',author:'Jose Rizal'})).status).toBe(201);expect((await request(manager).put('/api/v1/library/books/11111111-1111-4111-8111-111111111111').send({version:1,title:'Noli Me Tangere — Updated'})).status).toBe(200)});
  it('denies catalog writes to a view-only user',async()=>{const viewer=app(['library.portal.access','library.catalog.view']);expect((await request(viewer).post('/api/v1/library/books').send({title:'Noli Me Tangere',author:'Jose Rizal'})).status).toBe(403)});
  it('adds one or many copies only with copy management access',async()=>{const add=vi.spyOn(libraryCatalogRepository,'addCopies').mockResolvedValue({copies:[{id:'one'},{id:'two'}]});const manager=app(['library.portal.access','library.copies.manage']);const response=await request(manager).post('/api/v1/library/books/11111111-1111-4111-8111-111111111111/copies').send({quantity:2,condition:'good'});expect(response.status).toBe(201);expect(add).toHaveBeenCalledWith(expect.any(String),expect.objectContaining({quantity:2}),expect.any(Object));expect((await request(app(['library.portal.access','library.copies.view'])).post('/api/v1/library/books/11111111-1111-4111-8111-111111111111/copies').send({quantity:1})).status).toBe(403)});
  it('supports normalized barcode lookup for copy viewers',async()=>{const lookup=vi.spyOn(libraryCatalogRepository,'barcodeLookup').mockResolvedValue({id:'copy'});const response=await request(app(['library.portal.access','library.copies.view'])).get('/api/v1/library/copies/barcode/%20lib-000001%20');expect(response.status).toBe(200);expect(lookup).toHaveBeenCalledWith(' lib-000001 ')});
  it('requires copy management for status changes',async()=>{vi.spyOn(libraryCatalogRepository,'changeCopyStatus').mockResolvedValue({id:'copy',status:'damaged',version:2});const copy='11111111-1111-4111-8111-111111111111';expect((await request(app(['library.portal.access','library.copies.manage'])).post(`/api/v1/library/copies/${copy}/status`).send({version:1,status:'damaged'})).status).toBe(200);expect((await request(app(['library.portal.access','library.copies.view'])).post(`/api/v1/library/copies/${copy}/status`).send({version:1,status:'damaged'})).status).toBe(403)});
  it('edits copy metadata without accepting status in the payload',async()=>{const update=vi.spyOn(libraryCatalogRepository,'updateCopy').mockResolvedValue({id:'copy',version:2});const copy='11111111-1111-4111-8111-111111111111',manager=app(['library.portal.access','library.copies.manage']);expect((await request(manager).put(`/api/v1/library/copies/${copy}`).send({version:1,barcode:'LIB-MANUAL-1',condition:'fair'})).status).toBe(200);expect(update).toHaveBeenCalled();expect((await request(manager).put(`/api/v1/library/copies/${copy}`).send({version:1,status:'available'})).status).toBe(400)});
  it('archives a title only through catalog management',async()=>{vi.spyOn(libraryCatalogRepository,'archiveBook').mockResolvedValue({ok:true});const book='11111111-1111-4111-8111-111111111111';expect((await request(app(['library.portal.access','library.catalog.manage'])).post(`/api/v1/library/books/${book}/archive`).send({version:1})).status).toBe(200);expect((await request(app(['library.portal.access','library.catalog.view'])).post(`/api/v1/library/books/${book}/archive`).send({version:1})).status).toBe(403)});
  it('protects credential resolution with patron view permission',async()=>{vi.spyOn(libraryCirculationRepository,'credential').mockResolvedValue({patron:{displayName:'Juan'}} as never);expect((await request(app(['library.portal.access','library.patrons.view'])).post('/api/v1/library/patrons/credential').send({credential:'school-card'})).status).toBe(200);expect((await request(app(['library.portal.access'])).post('/api/v1/library/patrons/credential').send({credential:'school-card'})).status).toBe(403)});
  it('supports atomic multi-copy checkout and rejects duplicate payload copies',async()=>{const checkout=vi.spyOn(libraryCirculationRepository,'checkout').mockResolvedValue({loans:[{id:'one'},{id:'two'}]} as never),id='11111111-1111-4111-8111-111111111111',id2='22222222-2222-4222-8222-222222222222',operator=app(['library.portal.access','library.circulation.checkout']);expect((await request(operator).post('/api/v1/library/circulation/checkout').send({patron:{patronType:'student',personId:id},copyIds:[id,id2]})).status).toBe(201);expect(checkout).toHaveBeenCalled();expect((await request(operator).post('/api/v1/library/circulation/checkout').send({patron:{patronType:'student',personId:id},copyIds:[id,id]})).status).toBe(400)});
  it('checks in by copy barcode without a patron and permission-gates override',async()=>{vi.spyOn(libraryCirculationRepository,'checkin').mockResolvedValue({returned:{title:'Noli'}} as never);expect((await request(app(['library.portal.access','library.circulation.checkin'])).post('/api/v1/library/circulation/checkin').send({barcode:'LIB-000001'})).status).toBe(200);const id='11111111-1111-4111-8111-111111111111';expect((await request(app(['library.portal.access','library.circulation.checkout'])).post('/api/v1/library/circulation/checkout').send({patron:{patronType:'student',personId:id},copyIds:[id],overrideReason:'Approved exception'})).status).toBe(403)});
  it('renews an active loan through its dedicated permission',async()=>{const renew=vi.spyOn(libraryCirculationRepository,'renew').mockResolvedValue({loan:{id:'loan'}} as never),id='11111111-1111-4111-8111-111111111111';expect((await request(app(['library.portal.access','library.circulation.renew'])).post(`/api/v1/library/circulation/loans/${id}/renew`).send({version:1})).status).toBe(200);expect(renew).toHaveBeenCalledWith(id,1,undefined,expect.any(Object))});
  it('separates visitor viewing, logging, and reporting permissions',async()=>{vi.spyOn(libraryVisitorRepository,'scan').mockResolvedValue({visit:{id:'visit'}} as never);vi.spyOn(libraryVisitorRepository,'list').mockResolvedValue({items:[],total:0});vi.spyOn(libraryVisitorRepository,'analytics').mockResolvedValue({summary:{}} as never);const portal=['library.portal.access'];expect((await request(app([...portal,'library.visitors.log'])).post('/api/v1/library/visitors/scan').send({mode:'entry',credential:'RFID-1'})).status).toBe(200);expect((await request(app([...portal,'library.visitors.view'])).post('/api/v1/library/visitors/scan').send({mode:'entry',credential:'RFID-1'})).status).toBe(403);expect((await request(app([...portal,'library.visitors.view'])).get('/api/v1/library/visitors?date=2026-08-27')).status).toBe(200);expect((await request(app([...portal,'library.visitors.reports'])).get('/api/v1/library/visitors/analytics?date=2026-08-27')).status).toBe(200)});
  it('returns the validation contract for an invalid analytics date',async()=>{const response=await request(app(['library.portal.access','library.visitors.reports'])).get('/api/v1/library/visitors/analytics?date=08%2F27%2F2026');expect(response.status).toBe(400);expect(response.body.error.code).toBe('VALIDATION_ERROR')});
});
import{libraryOverdueRepository}from'../library/overdue-repository.js';
import{libraryNotificationRepository}from'../library/notification-repository.js';
import{libraryReportRepository}from'../library/report-repository.js';
describe('Library overdue RBAC',()=>{afterEach(()=>vi.restoreAllMocks());it('permission-gates queue reads and notification triggers',async()=>{vi.spyOn(libraryOverdueRepository,'list').mockResolvedValue({items:[],total:0});vi.spyOn(libraryNotificationRepository,'run').mockResolvedValue({candidates:0,created:0});const base=['library.portal.access'];expect((await request(app([...base,'library.overdue.view'])).get('/api/v1/library/overdue?category=overdue_1_7')).status).toBe(200);expect((await request(app([...base,'library.overdue.view'])).post('/api/v1/library/overdue/notifications/run')).status).toBe(403);expect((await request(app([...base,'library.overdue.manage'])).post('/api/v1/library/overdue/notifications/run')).status).toBe(200)})});
describe('Library reports RBAC',()=>{afterEach(()=>vi.restoreAllMocks());it('requires report view and independently protects CSV export',async()=>{vi.spyOn(libraryReportRepository,'run').mockResolvedValue({items:[{title:'Noli Me Tangere'}],total:1});const url='/api/v1/library/reports?report=inventory&from=2026-08-01&to=2026-08-31';expect((await request(app(['library.portal.access'])).get(url)).status).toBe(403);expect((await request(app(['library.portal.access','library.reports.view'])).get(url)).status).toBe(200);expect((await request(app(['library.portal.access','library.reports.view'])).get(`${url}&format=csv`)).status).toBe(403);const csv=await request(app(['library.portal.access','library.reports.view','report.export'])).get(`${url}&format=csv`);expect(csv.status).toBe(200);expect(csv.text).toContain('Noli Me Tangere')})});
