import express from 'express';
import request from 'supertest';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { pool } from '../database/pool.js';
import { errorHandler } from '../lib/errors.js';
import { storage } from '../media/storage.js';
import { requestContext } from '../middleware/request-context.js';
import { mediaRouter } from './media.js';

const userId='08f35c64-1fd8-4c59-abd9-03466935c97b';
const ownerId='c7681b64-082b-4c66-a7a7-b8df72aac35c';
const assetId='4af20f5d-53b8-498f-ac31-518db5ca9f12';
const image=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="2" height="2"><path fill="#fff" d="M0 0h2v2H0z"/></svg>');
function app(permissions:string[]){const value=express();value.use(requestContext,(req,_res,next)=>{req.auth={authenticated:true,userId,sessionId:'test',email:'admin@mmsc.test',displayName:'Admin',roles:['test'],permissions};next()});value.use('/api/v1',mediaRouter);value.use(errorHandler);return value;}
function mediaClient(old?:{storage_key:string;thumbnail_key:string}){const query=vi.fn(async(sql:string)=>{if(sql.includes('SELECT m.storage_key'))return{rows:[old??{storage_key:null,thumbnail_key:null}]};if(sql.startsWith('INSERT INTO media_assets'))return{rows:[{id:assetId}]};return{rows:[],rowCount:1};});const release=vi.fn();vi.spyOn(pool,'connect').mockResolvedValue({query,release} as never);return{query,release};}

afterEach(()=>vi.restoreAllMocks());

describe('managed profile media routes',()=>{
  it('resolves the Student owner URL to the current immutable asset',async()=>{vi.spyOn(pool,'query').mockResolvedValue({rows:[{profile_photo_asset_id:assetId}]} as never);const response=await request(app(['student.profile.view'])).get(`/api/v1/media/students/${ownerId}/profile-photo`);expect(response.status).toBe(302);expect(response.headers.location).toBe(`/api/v1/media/${assetId}/profile`);expect(response.headers['cache-control']).toContain('no-store');});
  it('resolves the Employee owner URL through the same implementation',async()=>{vi.spyOn(pool,'query').mockResolvedValue({rows:[{profile_photo_asset_id:assetId}]} as never);const response=await request(app(['employee.view'])).get(`/api/v1/media/employees/${ownerId}/profile-photo`);expect(response.status).toBe(302);expect(response.headers.location).toBe(`/api/v1/media/${assetId}/profile`);});
  it('returns an empty success state when the Student has no photo',async()=>{vi.spyOn(pool,'query').mockResolvedValue({rows:[{profile_photo_asset_id:null}]} as never);const response=await request(app(['student.profile.view'])).get(`/api/v1/media/students/${ownerId}/profile-photo`);expect(response.status).toBe(204);expect(response.body).toEqual({});expect(response.headers['cache-control']).toContain('no-store');});
  it('protects owner photo reads with domain view permission',async()=>{const query=vi.spyOn(pool,'query');const response=await request(app([])).get(`/api/v1/media/students/${ownerId}/profile-photo`);expect(response.status).toBe(403);expect(query).not.toHaveBeenCalled();});
  it('protects Student photo uploads with profile management permission',async()=>{const connect=vi.spyOn(pool,'connect');const response=await request(app([])).post(`/api/v1/media/students/${ownerId}/profile-photo`).attach('photo',Buffer.from('not processed'),{filename:'photo.png',contentType:'image/png'});expect(response.status).toBe(403);expect(connect).not.toHaveBeenCalled();});
  it('creates the first Student photo without requiring an existing asset',async()=>{const client=mediaClient();const upload=vi.spyOn(storage,'upload').mockResolvedValue();const remove=vi.spyOn(storage,'delete').mockResolvedValue();const response=await request(app(['student.profile.manage'])).post(`/api/v1/media/students/${ownerId}/profile-photo`).attach('photo',image,{filename:'photo.png',contentType:'image/png'});expect(response.status).toBe(201);expect(response.body.item).toMatchObject({id:assetId,profileUrl:`/media/${assetId}/profile`,thumbnailUrl:`/media/${assetId}/thumbnail`});expect(upload).toHaveBeenCalledTimes(2);expect(remove).not.toHaveBeenCalled();expect(client.query.mock.calls.some(([sql])=>String(sql).includes('UPDATE students SET profile_photo_asset_id=$1'))).toBe(true);expect(client.release).toHaveBeenCalled();});
  it('replaces an existing Student photo and removes the superseded files after commit',async()=>{mediaClient({storage_key:'profiles/old-profile.webp',thumbnail_key:'profiles/old-thumbnail.webp'});vi.spyOn(storage,'upload').mockResolvedValue();const remove=vi.spyOn(storage,'delete').mockResolvedValue();const response=await request(app(['student.profile.manage'])).post(`/api/v1/media/students/${ownerId}/profile-photo`).attach('photo',image,{filename:'replacement.webp',contentType:'image/webp'});expect(response.status).toBe(201);expect(remove).toHaveBeenCalledWith('profiles/old-profile.webp');expect(remove).toHaveBeenCalledWith('profiles/old-thumbnail.webp');});
  it('serves the optimized asset with its WebP content type',async()=>{vi.spyOn(pool,'query').mockResolvedValue({rows:[{storage_key:'profiles/a.webp',thumbnail_key:'profiles/b.webp'}]} as never);vi.spyOn(storage,'read').mockResolvedValue(Buffer.from('webp'));const response=await request(app([])).get(`/api/v1/media/${assetId}/profile`);expect(response.status).toBe(200);expect(response.headers['content-type']).toContain('image/webp');expect(response.body).toEqual(Buffer.from('webp'));});
  it('distinguishes unsupported and oversized uploads',async()=>{const invalid=await request(app(['student.profile.manage'])).post(`/api/v1/media/students/${ownerId}/profile-photo`).attach('photo',Buffer.from('%PDF- invalid'),{filename:'photo.pdf',contentType:'application/pdf'});expect(invalid.status).toBe(400);expect(invalid.body.error.code).toBe('INVALID_IMAGE_TYPE');const oversized=await request(app(['student.profile.manage'])).post(`/api/v1/media/students/${ownerId}/profile-photo`).attach('photo',Buffer.alloc(5*1024*1024+1),{filename:'photo.jpg',contentType:'image/jpeg'});expect(oversized.status).toBe(400);expect(oversized.body.error.code).toBe('INVALID_UPLOAD');});
});
