import express from'express';import request from'supertest';import{afterEach,describe,expect,it,vi}from'vitest';import{dashboardRepository}from'../dashboard/repository.js';import{reportingRepository}from'../reporting/repository.js';import{errorHandler}from'../lib/errors.js';import{requestContext}from'../middleware/request-context.js';import{reportingRouter}from'./reporting.js';
function app(permissions:string[]){const instance=express();instance.use(express.json(),requestContext,(request,_response,next)=>{request.auth={userId:'08f35c64-1fd8-4c59-abd9-03466935c97b',authenticated:true,sessionId:'x',email:'admin@mmsc.test',displayName:'Admin',roles:['school_administrator'],permissions};next()});instance.use('/api/v1',reportingRouter);instance.use(errorHandler);return instance}
afterEach(()=>vi.restoreAllMocks());
describe('Phase 25 reporting routes',()=>{
 it('returns a permission-scoped operational dashboard model',async()=>{const dashboard=vi.spyOn(dashboardRepository,'overview').mockResolvedValue({access:{students:true}} as never);const response=await request(app(['dashboard.view','student.profile.view'])).get('/api/v1/dashboard/admin');expect(response.status).toBe(200);expect(response.body.access.students).toBe(true);expect(dashboard).toHaveBeenCalledWith(expect.objectContaining({students:true,employees:false,teachers:false,admissions:false}))});
 it('derives teacher visibility only when both teacher and employee attendance access exist',async()=>{const dashboard=vi.spyOn(dashboardRepository,'overview').mockResolvedValue({} as never);await request(app(['dashboard.view','teacher.profile.view'])).get('/api/v1/dashboard/admin');expect(dashboard).toHaveBeenCalledWith(expect.objectContaining({teachers:false}));await request(app(['dashboard.view','teacher.profile.view','employee.attendance.view'])).get('/api/v1/dashboard/admin');expect(dashboard).toHaveBeenLastCalledWith(expect.objectContaining({teachers:true}))});
 it('exports CSV only with export permission',async()=>{vi.spyOn(reportingRepository,'report').mockResolvedValue([{gradeLevel:'Grade 1',students:2}]);const url='/api/v1/reports/enrollment-by-grade?from=2026-01-01&to=2026-12-31&format=csv';expect((await request(app(['report.view'])).get(url)).status).toBe(403);const ok=await request(app(['report.view','report.export'])).get(url);expect(ok.status).toBe(200);expect(ok.text).toContain('Grade 1')});
 it('accepts an implemented-domain analytics report',async()=>{const report=vi.spyOn(reportingRepository,'report').mockResolvedValue([{status:'submitted',applications:3}]);const response=await request(app(['report.view'])).get('/api/v1/reports/admissions-pipeline?from=2026-01-01&to=2026-12-31');expect(response.status).toBe(200);expect(response.body.generatedAt).toBeTruthy();expect(report).toHaveBeenCalledWith('admissions-pipeline','2026-01-01','2026-12-31')});
 it('rejects an invalid date interval',async()=>{expect((await request(app(['report.view'])).get('/api/v1/reports/events-summary?from=2026-12-31&to=2026-01-01')).status).toBe(400)});
 it('rejects deferred-domain report names',async()=>{expect((await request(app(['report.view'])).get('/api/v1/reports/library-circulation?from=2026-01-01&to=2026-12-31')).status).toBe(400)});
 it('protects centralized settings',async()=>{expect((await request(app(['dashboard.view'])).get('/api/v1/administration/settings')).status).toBe(403)});
});
