import express from 'express';import request from 'supertest';import{afterEach,describe,expect,it,vi}from'vitest';import{studentAttendanceRepository}from'../student-attendance/repository.js';import{errorHandler}from'../lib/errors.js';import{requestContext}from'../middleware/request-context.js';import{studentAttendanceRouter}from'./student-attendance.js';
function app(p:string[]){const a=express();a.use(express.json());a.use(requestContext);a.use((r,_s,n)=>{r.auth={userId:'08f35c64-1fd8-4c59-abd9-03466935c97b',authenticated:true,sessionId:'x',email:'registrar@mmsc.test',displayName:'Registrar',roles:['registrar'],permissions:p};n();});a.use('/api/v1',studentAttendanceRouter);a.use(errorHandler);return a;}
afterEach(()=>vi.restoreAllMocks());
describe('Phase 9 student attendance routes',()=>{
 it('lists only supported attendance-record statuses',async()=>{const list=vi.spyOn(studentAttendanceRepository,'list').mockResolvedValue({items:[],total:0,page:1,limit:25});const r=await request(app(['student.attendance.view'])).get('/api/v1/attendance/students?from=2026-08-24&to=2026-08-24&status=present&page=1&limit=25');expect(r.status).toBe(200);expect(r.body).toEqual({items:[],total:0,page:1,limit:25});expect(list).toHaveBeenCalledWith(expect.objectContaining({from:'2026-08-24',to:'2026-08-24',status:'present',page:1,limit:25}));});
 it('rejects the former synthetic not-recorded status',async()=>{const list=vi.spyOn(studentAttendanceRepository,'list');const r=await request(app(['student.attendance.view'])).get('/api/v1/attendance/students?from=2026-08-24&to=2026-08-24&status=not_recorded');expect(r.status).toBe(400);expect(list).not.toHaveBeenCalled();});
 it('protects administrative adjustments',async()=>{const r=await request(app(['student.attendance.view'])).post('/api/v1/attendance/students/08f35c64-1fd8-4c59-abd9-03466935c97b/adjustments').send({});expect(r.status).toBe(403);});
 it('rejects class scope without an assignment',async()=>{const r=await request(app(['student.attendance.manage'])).post('/api/v1/attendance/students').send({enrollmentId:'08f35c64-1fd8-4c59-abd9-03466935c97b',attendanceDate:'2026-08-19',attendanceScope:'class',status:'present',source:'manual'});expect(r.status).toBe(400);});
});
