import { Router, type Request } from 'express';
import { z } from 'zod';
import { AppError } from '../lib/errors.js';
import { requirePermission } from '../security/middleware.js';
import { teacherRepository } from '../teachers/repository.js';
import { qualificationSchema, teacherProfileSchema, teacherProfileUpdateSchema, yearAssignmentSchema } from '../teachers/schemas.js';

export const teachersRouter=Router(); const id=z.string().uuid(); const version=z.coerce.number().int().positive();
const ip=(value:string|undefined)=>value?.replace(/^::ffff:/,''); const ctx=(req:Request)=>({actorId:req.auth.userId!,requestId:String(req.id),ip:ip(req.ip)}); const stale=()=>new AppError(409,'STALE_RECORD','The record changed or no longer exists');

teachersRouter.get('/teachers/context',requirePermission('teacher.profile.view'),async(_req,res,next)=>{try{res.json(await teacherRepository.context());}catch(error){next(error);}});
teachersRouter.get('/teachers/eligible-employees',requirePermission('teacher.profile.manage'),async(req,res,next)=>{try{const query=z.object({search:z.string().trim().max(160).default('')}).parse(req.query);res.json({items:await teacherRepository.eligibleEmployees(query.search)});}catch(error){next(error);}});
teachersRouter.get('/teachers',requirePermission('teacher.profile.view'),async(req,res,next)=>{try{const blank=(value:unknown)=>value===''?undefined:value;const query=z.object({search:z.preprocess(blank,z.string().trim().max(160).optional()),departmentId:z.preprocess(blank,id.optional()),facultyStatus:z.preprocess(blank,z.enum(['full_time','part_time','adjunct','substitute','inactive']).optional()),employmentStatus:z.preprocess(blank,z.enum(['active','on_leave','inactive','terminated']).optional()),gradeLevelId:z.preprocess(blank,id.optional()),sectionId:z.preprocess(blank,id.optional()),subjectId:z.preprocess(blank,id.optional()),sort:z.enum(['teacher_asc','teacher_desc','number_asc']).default('teacher_asc'),limit:z.coerce.number().int().min(1).max(100).default(25),offset:z.coerce.number().int().min(0).default(0)}).parse(req.query);res.json(await teacherRepository.list(query));}catch(error){next(error);}});
teachersRouter.post('/teachers',requirePermission('teacher.profile.manage'),async(req,res,next)=>{try{res.status(201).json({item:await teacherRepository.create(teacherProfileSchema.parse(req.body),ctx(req))});}catch(error){next(error);}});
teachersRouter.get('/teachers/:id',requirePermission('teacher.profile.view'),async(req,res,next)=>{try{const teacherId=id.parse(req.params.id);const item=await teacherRepository.detail(teacherId);if(!item)throw new AppError(404,'TEACHER_NOT_FOUND','Teacher was not found');await teacherRepository.access(teacherId,ctx(req));if(!req.auth.permissions.includes('teacher.qualification.view'))item.qualifications=[];if(!req.auth.permissions.includes('teacher.year_assignment.view'))item.yearAssignments=[];if(!req.auth.permissions.includes('academic.assignment.view'))item.teachingAssignments=[];if(!req.auth.permissions.includes('audit.view'))item.history=[];res.json(item);}catch(error){next(error);}});
teachersRouter.patch('/teachers/:id',requirePermission('teacher.profile.manage'),async(req,res,next)=>{try{const body=z.object({version,data:teacherProfileUpdateSchema}).strict().parse(req.body);const item=await teacherRepository.update(id.parse(req.params.id),body.version,body.data,ctx(req));if(!item)throw stale();res.json({item});}catch(error){next(error);}});
teachersRouter.delete('/teachers/:id',requirePermission('teacher.profile.manage'),async(req,res,next)=>{try{if(!await teacherRepository.archive(id.parse(req.params.id),version.parse(req.query.version),ctx(req)))throw stale();res.status(204).end();}catch(error){next(error);}});

for(const kind of ['qualifications','year-assignments'] as const){const schema=kind==='qualifications'?qualificationSchema:yearAssignmentSchema;const permission=kind==='qualifications'?'teacher.qualification.manage':'teacher.year_assignment.manage';teachersRouter.post(`/teachers/:id/${kind}`,requirePermission(permission),async(req,res,next)=>{try{res.status(201).json({item:await teacherRepository.createRelated(kind,id.parse(req.params.id),schema.parse(req.body),ctx(req))});}catch(error){next(error);}});teachersRouter.patch(`/teachers/${kind}/:id`,requirePermission(permission),async(req,res,next)=>{try{const body=z.object({version,data:schema}).strict().parse(req.body);const item=await teacherRepository.updateRelated(kind,id.parse(req.params.id),body.version,body.data,ctx(req));if(!item)throw stale();res.json({item});}catch(error){next(error);}});teachersRouter.delete(`/teachers/${kind}/:id`,requirePermission(permission),async(req,res,next)=>{try{if(!await teacherRepository.archiveRelated(kind,id.parse(req.params.id),version.parse(req.query.version),ctx(req)))throw stale();res.status(204).end();}catch(error){next(error);}});}
