import { api, ApiError } from './api';
import { deleteCapture, pendingCaptures, readDevice, replaceCredentials, updateCapture, writeMeta, type Capture, type CachedCredential } from './storage';
type Result={captureId:string;outcome:'accepted'|'rejected';message:string;syncStatus?:'synced'|'already_processed'|'duplicate_scan'|'rejected';attendanceStatus?:string;displayName?:string;identifier?:string;profilePhotoUrl?:string;subjectType?:'student'|'employee';capturedAt?:string};
export type SyncReport={results:Result[];pending:number};
const delays=[0,5000,15000,30000,60000,120000,300000];
export class SyncEngine{
 private active:Promise<SyncReport>|null=null;private timer:number|undefined;private failures=0;private lastCredentialSync=0;
 constructor(private notify:(report:SyncReport)=>void=()=>undefined){}
 async credentials(){const device=await readDevice();if(!device)return;const response=await api<{items:CachedCredential[];synchronizedAt:string}>('/attendance-terminals/runtime/credentials',{headers:{authorization:`Device ${device.deviceCredential}`}});await replaceCredentials(response.items,response.synchronizedAt);this.lastCredentialSync=Date.now()}
 run(manual=false){if(this.active)return this.active;if(manual&&this.timer!==undefined){clearTimeout(this.timer);this.timer=undefined}this.active=this.execute(manual).finally(()=>{this.active=null});return this.active}
 private async execute(manual:boolean){if(manual||Date.now()-this.lastCredentialSync>=300000)await this.credentials();const device=await readDevice(),captures=(await pendingCaptures()).slice(0,100);if(!device||!captures.length)return{results:[],pending:captures.length};const now=new Date().toISOString();for(const item of captures)await updateCapture({...item,syncState:'syncing',syncAttemptCount:item.syncAttemptCount+1,lastSyncAttemptAt:now,lastSyncError:null});try{const response=await api<{results:Result[]}>('/attendance-terminals/runtime/sync',{method:'POST',headers:{authorization:`Device ${device.deviceCredential}`},body:JSON.stringify({captures:captures.map(({captureId,credentialValue,captureMethod,capturedAt})=>({captureId,credentialValue,captureMethod,capturedAt}))})});const byId=new Map(response.results.map(x=>[x.captureId,x]));for(const capture of captures){const result=byId.get(capture.captureId);if(!result)await this.retry(capture,'No receipt returned');else if(result.outcome==='accepted')await deleteCapture(capture.captureId);else await updateCapture({...capture,syncState:'failed_permanent',lastSyncAttemptAt:now,lastSyncError:result.message})}this.failures=0;await writeMeta('lastSuccessfulSync',now);const report={results:response.results,pending:(await pendingCaptures()).length};this.notify(report);return report}catch(error){for(const capture of captures)await this.retry(capture,error instanceof Error?error.message:'Synchronization failed');if(error instanceof ApiError&&['TERMINAL_DEVICE_REVOKED','TERMINAL_DEVICE_CREDENTIAL_INVALID','TERMINAL_DISABLED'].includes(error.code))throw error;this.schedule();throw error}}
 private retry(capture:Capture,message:string){return updateCapture({...capture,syncState:'failed_retryable',lastSyncError:message,lastSyncAttemptAt:new Date().toISOString()})}
 private schedule(){const base=delays[Math.min(++this.failures,delays.length-1)]!,jitter=Math.round(base*.2*Math.random());this.timer=window.setTimeout(()=>void this.run().catch(()=>undefined),base+jitter)}
}
