import { useCallback,useEffect,useMemo,useRef,useState,type FormEvent,type ReactNode } from 'react';
import { Camera,CheckCircle2,CloudOff,Info,KeyRound,Menu,RefreshCw,ScanLine,ShieldAlert,UserRound,Wifi,XCircle } from 'lucide-react';
import { api,ApiError } from './api';
import { predictAttendance } from './attendance-sequence';
import { HidScanner,normalizeCredentialValue,validateCachedCredential } from './scanner';
import { SyncEngine,type SyncReport } from './sync';
import { clearDevice,enqueueCapture,pendingCaptures,readConfig,readDevice,readMeta,resolveCredential,saveConfig,saveDevice,type DeviceIdentity,type TerminalConfig } from './storage';

const version='2.0.0',duplicateWindow=60000;
type RuntimeState='UNPROVISIONED'|'INITIALIZING'|'READY'|'OFFLINE'|'SYNCING'|'DISABLED'|'REVOKED'|'ERROR';
type Result={ok:boolean;title:string;name?:string;identifier?:string;personType?:string;capturedAt?:string;offline?:boolean;photo?:string|null};

export function TerminalApp(){
 const[device,setDevice]=useState<DeviceIdentity|null>(),[config,setConfig]=useState<TerminalConfig|null>(),[state,setState]=useState<RuntimeState>('INITIALIZING'),[pending,setPending]=useState(0),[result,setResult]=useState<Result|null>(null),[menu,setMenu]=useState(false),[diagnostics,setDiagnostics]=useState(false),[error,setError]=useState(''),[clock,setClock]=useState(new Date()),[input,setInput]=useState('');
 const lastScan=useRef<{value:string;at:number}|null>(null),resultTimer=useRef<number|undefined>(undefined),engine=useMemo(()=>new SyncEngine((report:SyncReport)=>{setPending(report.pending);setState(navigator.onLine?'READY':'OFFLINE')}),[]);
 const auth=useCallback((identity:DeviceIdentity)=>({authorization:`Device ${identity.deviceCredential}`}),[]);
 const bootstrap=useCallback(async(identity:DeviceIdentity)=>{try{const response=await api<{item:TerminalConfig}>('/attendance-terminals/runtime/bootstrap',{headers:auth(identity)});await saveConfig(response.item);setConfig(response.item);await engine.credentials();setState('READY');setError('');void engine.run().catch(()=>undefined)}catch(cause){if(cause instanceof ApiError&&cause.code==='TERMINAL_DEVICE_REVOKED')setState('REVOKED');else if(cause instanceof ApiError&&cause.code==='TERMINAL_DISABLED')setState('DISABLED');else{const cached=await readConfig();if(cached){setConfig(cached);setState('OFFLINE')}else{setState('ERROR');setError('Configuration is not available on this device. Connect to MMSC and try again.')}}}},[auth,engine]);
 useEffect(()=>{let active=true;void Promise.all([readDevice(),readConfig(),pendingCaptures()]).then(([identity,cached,captures])=>{if(!active)return;setDevice(identity);setConfig(cached);setPending(captures.length);if(!identity){setState('UNPROVISIONED');return}if(cached)setState(navigator.onLine?'INITIALIZING':'OFFLINE');if(navigator.onLine)void bootstrap(identity);else setState(cached?'OFFLINE':'ERROR')});const tick=setInterval(()=>setClock(new Date()),1000);return()=>{active=false;clearInterval(tick);if(resultTimer.current)clearTimeout(resultTimer.current)}},[bootstrap]);
 useEffect(()=>{const changed=()=>{if(!device)return;if(navigator.onLine){setState('SYNCING');void bootstrap(device)}else setState('OFFLINE')},visible=()=>{if(document.visibilityState==='visible'&&navigator.onLine&&device)void engine.run().catch(()=>undefined)};addEventListener('online',changed);addEventListener('offline',changed);document.addEventListener('visibilitychange',visible);const timer=setInterval(()=>{if(navigator.onLine&&device)void engine.run().then(report=>setPending(report.pending)).catch(()=>undefined)},30000);return()=>{removeEventListener('online',changed);removeEventListener('offline',changed);document.removeEventListener('visibilitychange',visible);clearInterval(timer)}},[bootstrap,device,engine]);
 const show=useCallback((next:Result)=>{setResult(next);if(resultTimer.current)clearTimeout(resultTimer.current);resultTimer.current=window.setTimeout(()=>setResult(null),5000)},[]);
 const scan=useCallback(async(raw:string)=>{
  const value=normalizeCredentialValue(raw);if(!value||!device||!config||!['READY','OFFLINE'].includes(state))return;
  const now=Date.now();if(lastScan.current?.value===value&&now-lastScan.current.at<duplicateWindow){show({ok:false,title:'Already recorded — please wait'});return}lastScan.current={value,at:now};
  const cached=await resolveCredential(value);if(!cached){console.info('Attendance credential rejected',{reason:'CREDENTIAL_NOT_FOUND'});show({ok:false,title:'Credential not recognized.'});return}
  const validation=validateCachedCredential(cached,now);if(!validation.valid){console.info('Attendance credential rejected',{reason:validation.reason,credentialId:cached.credentialId,ownerType:cached.identityType,ownerId:cached.identityId});show({ok:false,title:validation.message});return}
  const capturedAt=new Date().toISOString(),queued=await pendingCaptures(),prediction=predictAttendance(cached,queued,value,capturedAt);if(prediction.duplicate){show({ok:false,title:'Already recorded — please wait',name:cached.displayName,identifier:cached.identifier,personType:cached.identityType,capturedAt:prediction.latestAt??capturedAt,photo:cached.profilePhotoUrl});return}
  try{const captureId=crypto.randomUUID();await enqueueCapture({captureId,terminalId:config.terminalId,credentialValue:value,captureMethod:cached.credentialType,capturedAt});const count=(await pendingCaptures()).length;setPending(count);
   if(!navigator.onLine){show({ok:true,title:prediction.direction==='time_in'?'TIME IN':'TIME OUT',name:cached.displayName,identifier:cached.identifier,personType:cached.identityType,capturedAt,offline:true,photo:cached.profilePhotoUrl});return}
   void engine.run().then(report=>{setPending(report.pending);const receipt=report.results.find(item=>item.captureId===captureId);if(!receipt)return;const duplicate=receipt.attendanceStatus==='duplicate';show({ok:receipt.outcome==='accepted',title:duplicate?'Already recorded — please wait':receipt.attendanceStatus==='time_in'?'TIME IN':receipt.attendanceStatus==='time_out'?'TIME OUT':receipt.message,name:receipt.displayName??cached.displayName,identifier:receipt.identifier??cached.identifier,personType:receipt.subjectType??cached.identityType,capturedAt:receipt.capturedAt??capturedAt,photo:receipt.profilePhotoUrl??cached.profilePhotoUrl})}).catch(()=>undefined)
  }catch{show({ok:false,title:'Unable to save attendance. Please scan again.'})}
 },[config,device,engine,show,state]);
 useEffect(()=>{const adapter=new HidScanner(value=>void scan(value)),key=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement||event.ctrlKey||event.altKey||event.metaKey)return;adapter.key(event.key,event.timeStamp)};addEventListener('keydown',key,true);return()=>removeEventListener('keydown',key,true)},[scan]);
 if(state==='INITIALIZING'||device===undefined)return <Setup title="Preparing attendance terminal" message="Restoring the device, credential snapshot, and queued attendance."/>;
 if(state==='UNPROVISIONED')return <Provision onComplete={(identity,next)=>{setDevice(identity);setConfig(next);setState('READY')}}/>;
 if(state==='REVOKED'||state==='DISABLED')return <Setup icon={<ShieldAlert/>} title={state==='REVOKED'?'Device Requires Reprovisioning':'Device Disabled'} message={state==='REVOKED'?'This device was revoked by MMSC. Ask an administrator for a new provisioning code.':'This terminal has been disabled. Please contact an authorized administrator.'}/>;
 if(state==='ERROR'||!device||!config)return <Setup title="Terminal unavailable" message={error||'Connect to MMSC to finish preparing this device.'}/>;
 const online=state!=='OFFLINE',status=state==='SYNCING'?`Syncing · ${pending} queued`:online?(pending?`Online · ${pending} retrying`:'Online · Synced'):`Offline · ${pending} queued`;
 const submit=(event:FormEvent)=>{event.preventDefault();const value=input;setInput('');void scan(value)};
 const syncNow=()=>{setState('SYNCING');void engine.run(true).then(report=>{setPending(report.pending);setState(navigator.onLine?'READY':'OFFLINE')}).catch(cause=>{if(cause instanceof ApiError&&cause.code==='TERMINAL_DEVICE_REVOKED')setState('REVOKED');else setState(navigator.onLine?'READY':'OFFLINE')});setMenu(false)};
 const reprovision=async()=>{if(!confirm('Reprovision this device? Pending attendance remains on this device but capture will stop until provisioning completes.'))return;await clearDevice();setDevice(null);setConfig(null);setState('UNPROVISIONED')};
 return <div className="terminal"><header><span><img src="/mmsc-logo.jpg" alt="MMSC crest"/><strong>MMSC Attendance</strong></span><div className={online?'online':'offline'}>{online?<Wifi/>:<CloudOff/>}{status}</div><button aria-label="Terminal menu" onClick={()=>setMenu(!menu)}><Menu/></button>{menu&&<nav className="terminal-menu"><strong>{config.name}</strong><small>{config.location??'MMSC attendance terminal'}</small><button onClick={syncNow} disabled={state==='SYNCING'}><RefreshCw/>Sync Now</button><button onClick={()=>{setDiagnostics(true);setMenu(false)}}><Info/>Terminal Information</button><button onClick={()=>void reprovision()}><KeyRound/>Change Terminal / Reprovision</button></nav>}</header><main><section className="terminal-status"><span className="terminal-location">{config.name} · {config.location??'Location not specified'}</span><time className="terminal-clock">{clock.toLocaleTimeString('en-PH',{hour:'numeric',minute:'2-digit',second:'2-digit'})}</time><p>{clock.toLocaleDateString('en-PH',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</p>{result?<ResultView result={result}/>:<><ScanLine/><h1>Ready to Scan</h1><p>Tap or scan your School ID. RFID and QR readers remain active continuously.</p><button className="camera-button" disabled><Camera/>QR camera setup pending</button></>}<form className="terminal-manual-test" onSubmit={submit}><label htmlFor="credential"><strong>RFID / QR Test Input</strong><small>Uses the same secure credential pipeline as a reader</small></label><div><input id="credential" value={input} onChange={e=>setInput(e.target.value)} autoComplete="off"/><button disabled={!input.trim()}>Process Credential</button></div></form></section><div className="terminal-sync-summary"><span>{online?'Automatic synchronization active':'Attendance is stored securely on this device'}</span><span>{pending} {pending===1?'attendance record':'attendance records'} waiting to sync</span></div></main>{diagnostics&&<Diagnostics device={device} config={config} pending={pending} state={state} close={()=>setDiagnostics(false)}/>}</div>;
}

function Provision({onComplete}:{onComplete:(device:DeviceIdentity,config:TerminalConfig)=>void}){const[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),deviceIdentifier=crypto.randomUUID();setBusy(true);setError('');try{const response=await api<{item:{deviceId:string;terminalId:string;deviceCredential:string}}>('/attendance-terminals/provision',{method:'POST',body:JSON.stringify({provisioningCode:String(form.get('code')).trim().toUpperCase(),deviceIdentifier,applicationVersion:version})});const identity:DeviceIdentity={...response.item,deviceIdentifier,provisionedAt:new Date().toISOString()};await saveDevice(identity);const boot=await api<{item:TerminalConfig}>('/attendance-terminals/runtime/bootstrap',{headers:{authorization:`Device ${identity.deviceCredential}`}});await saveConfig(boot.item);onComplete(identity,boot.item)}catch(cause){setError(cause instanceof ApiError?cause.message:'MMSC is unreachable. Provisioning requires a connection.')}finally{setBusy(false)}};return <main className="terminal-setup"><section><Brand/><span className="setup-mark"><KeyRound/></span><h1>Configure this device</h1><p>Scan a provisioning QR or enter the one-time code generated for this terminal in MMSC Administration.</p>{error&&<div className="setup-error" role="alert">{error}</div>}<form onSubmit={submit}><label>Provisioning code<input name="code" autoComplete="one-time-code" placeholder="MMSC-XXXX-XXXX" required autoFocus/></label><button disabled={busy}>{busy?'Provisioning…':'Provision Device'}</button></form><small className="setup-note">No administrator password is stored or required for daily attendance capture.</small></section></main>}
function Brand(){return <div className="setup-brand"><img src="/mmsc-logo.jpg" alt="MMSC crest"/><span><strong>My Messiah School of Cavite</strong><small>Attendance Terminal</small></span></div>}
function Setup({title,message,icon=<ScanLine/>}:{title:string;message:string;icon?:ReactNode}){return <main className="terminal-setup"><section><Brand/><span className="setup-mark">{icon}</span><h1>{title}</h1><p>{message}</p></section></main>}
function ResultView({result}:{result:Result}){return <div className={`terminal-identity-result ${result.ok?'success':'error'}`} role="status" aria-live="assertive"><span className="terminal-result-icon">{result.ok?<CheckCircle2/>:<XCircle/>}</span>{result.name&&<span className="terminal-result-photo">{result.photo?<img src={result.photo} alt=""/>:<UserRound/>}</span>}<div><strong>{result.title.toUpperCase()}</strong>{result.name&&<h1>{result.name}</h1>}{result.identifier&&<p>{result.personType==='student'?'Student':'Employee'} No. {result.identifier}</p>}{result.capturedAt&&<time>{new Date(result.capturedAt).toLocaleTimeString('en-PH',{hour:'numeric',minute:'2-digit'})}</time>}{result.offline&&<small>Will sync automatically</small>}</div></div>}
function Diagnostics({device,config,pending,state,close}:{device:DeviceIdentity;config:TerminalConfig;pending:number;state:RuntimeState;close:()=>void}){const[lastSync,setLastSync]=useState<string>();useEffect(()=>{void readMeta<string>('lastSuccessfulSync').then(setLastSync)},[]);return <div className="terminal-dialog" role="dialog" aria-modal="true" aria-labelledby="diagnostics-title"><section><h2 id="diagnostics-title">Terminal Information</h2><dl><dt>Terminal</dt><dd>{config.name}</dd><dt>Device ID</dt><dd>{device.deviceId}</dd><dt>Application</dt><dd>{version}</dd><dt>State</dt><dd>{state}</dd><dt>Credential snapshot</dt><dd>{config.credentialSnapshotVersion}</dd><dt>Queued captures</dt><dd>{pending}</dd><dt>Last successful sync</dt><dd>{lastSync?new Date(lastSync).toLocaleString('en-PH'):'Not yet synchronized'}</dd></dl><button onClick={close}>Close</button></section></div>}
