import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import { pinoHttp } from 'pino-http';
import { env } from './config/env.js';
import { errorHandler } from './lib/errors.js';
import { logger } from './lib/logger.js';
import { notFound } from './middleware/not-found.js';
import { requestContext } from './middleware/request-context.js';
import { healthRouter } from './routes/health.js';
import { authRouter } from './routes/auth.js';
import { securityRouter } from './routes/security.js';
import { authenticate, requirePasswordReady } from './security/middleware.js';
import { academicsRouter } from './routes/academics.js';
import { workforceRouter } from './routes/workforce.js';
import { teachersRouter } from './routes/teachers.js';
import { studentsRouter } from './routes/students.js';
import { enrollmentsRouter } from './routes/enrollments.js';
import { mediaRouter } from './routes/media.js';
import { assignmentsRouter } from './routes/assignments.js';
import { attendanceRouter } from './routes/attendance.js';
import { studentAttendanceRouter } from './routes/student-attendance.js';
import { reportingRouter } from './routes/reporting.js';
import { teacherPortalRouter } from './routes/teacher-portal.js';
import { gradingRouter } from './routes/grading.js';
import { studentPortalRouter } from './routes/student-portal.js';
import { terminalRouter } from './routes/terminal.js';
import { admissionsRouter } from './routes/admissions.js';
import { publicAdmissionsRouter } from './routes/public-admissions.js';
import { parentPortalRouter } from './routes/parent-portal.js';
import { notificationsRouter } from './routes/notifications.js';
import { attendanceOperationsRouter } from './routes/attendance-operations.js';
import { calendarRouter } from './routes/calendar.js';
import { enforceBrowserOrigin, preventSensitiveCaching } from './middleware/security-hardening.js';
import { operationalRouter } from './routes/operational.js';
import { referenceDataRouter } from './routes/reference-data.js';
import { credentialsRouter } from './routes/credentials.js';
import { clinicRouter } from './routes/clinic.js';
import { libraryRouter } from './routes/library.js';
import { computerLabRouter } from './routes/computer-lab.js';

export const createApp = () => {
  const app = express();
  app.disable('x-powered-by');
  app.set('trust proxy',env.TRUST_PROXY?1:false);
  app.use(requestContext);
  app.use(pinoHttp({ logger, customProps: (req) => ({ requestId: req.id }) }));
  app.use(helmet({ ...(env.NODE_ENV==='production'?{}:{strictTransportSecurity:false}), contentSecurityPolicy: { directives: { defaultSrc: ["'none'"], frameAncestors: ["'none'"], ...(env.NODE_ENV==='production'?{}:{upgradeInsecureRequests:null}) } } }));
  app.use(cors({ origin: env.CORS_ORIGIN.split(',').map((value) => value.trim()), credentials: true }));
  app.use(express.json({ limit: '1mb' }));
  app.use('/api/v1', preventSensitiveCaching, enforceBrowserOrigin);
  app.use('/api/v1', healthRouter);
  app.use('/api/v1', publicAdmissionsRouter);
  app.use('/api/v1', authenticate, authRouter, requirePasswordReady, securityRouter, referenceDataRouter, academicsRouter, calendarRouter, workforceRouter, teachersRouter, studentsRouter, enrollmentsRouter, assignmentsRouter, attendanceRouter, studentAttendanceRouter, attendanceOperationsRouter, reportingRouter, operationalRouter, teacherPortalRouter, gradingRouter, studentPortalRouter, credentialsRouter, terminalRouter, admissionsRouter, parentPortalRouter, notificationsRouter, clinicRouter, libraryRouter, computerLabRouter, mediaRouter);
  app.use(notFound);
  app.use(errorHandler);
  return app;
};
