import{pool}from'../database/pool.js';const camel=(v:string)=>v.replace(/_([a-z])/g,(_,x:string)=>x.toUpperCase());const map=(r:Record<string,unknown>)=>Object.fromEntries(Object.entries(r).map(([k,v])=>[camel(k),v]));const rows=async(q:string,v:unknown[]=[])=>(await pool.query(q,v)).rows.map(map);const scalar=async(q:string,v:unknown[]=[])=>Number((await pool.query(q,v)).rows[0]?.count??0);
export class ReportingRepository{
 async dashboard(includeActivity:boolean){const today=new Date().toISOString().slice(0,10);const[students,employees,teachers,enrollmentsByGrade,studentsBySection,employeeAttendance,studentAttendance,recentEnrollments,recentActivity]=await Promise.all([scalar(`SELECT count(*) FROM students WHERE archived_at IS NULL`),scalar(`SELECT count(*) FROM employees WHERE archived_at IS NULL AND employment_status='active'`),scalar(`SELECT count(*) FROM teacher_profiles tp JOIN employees e ON e.id=tp.employee_id WHERE tp.archived_at IS NULL AND e.archived_at IS NULL AND e.employment_status='active'`),rows(`SELECT g.name,count(*)::int count FROM enrollments e JOIN grade_levels g ON g.id=e.grade_level_id WHERE e.status IN ('pending','enrolled') GROUP BY g.id,g.name,g.sequence ORDER BY g.sequence`),rows(`SELECT COALESCE(s.name,'Unassigned') name,count(*)::int count FROM enrollments e LEFT JOIN sections s ON s.id=e.section_id WHERE e.status IN ('pending','enrolled') GROUP BY s.id,s.name ORDER BY s.name NULLS LAST`),rows(`SELECT status,count(*)::int count FROM employee_attendance_records WHERE archived_at IS NULL AND attendance_date=$1 GROUP BY status ORDER BY status`,[today]),rows(`SELECT status,count(*)::int count FROM student_attendance_records WHERE archived_at IS NULL AND attendance_date=$1 AND attendance_scope='campus' GROUP BY status ORDER BY status`,[today]),rows(`SELECT e.id,e.enrollment_date,s.student_number,s.first_name,s.last_name,sy.name school_year_name,g.name grade_level_name FROM enrollments e JOIN students s ON s.id=e.student_id JOIN school_years sy ON sy.id=e.school_year_id JOIN grade_levels g ON g.id=e.grade_level_id ORDER BY e.created_at DESC LIMIT 8`),includeActivity?rows(`SELECT a.id,a.action,a.target_type,a.outcome,a.occurred_at,u.display_name actor_name FROM audit_events a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.occurred_at DESC LIMIT 8`):Promise.resolve([])]);return{asOf:new Date().toISOString(),metrics:{students,activeEmployees:employees,activeTeachers:teachers},enrollmentsByGrade,studentsBySection,employeeAttendance,studentAttendance,recentEnrollments,recentActivity}}
 async report(type:string,from:string,to:string){
  if(type==='enrollment-by-grade')return rows(`SELECT sy.name school_year,g.code grade_code,g.name grade_level,count(*)::int students FROM enrollments e JOIN school_years sy ON sy.id=e.school_year_id JOIN grade_levels g ON g.id=e.grade_level_id WHERE e.enrollment_date BETWEEN $1 AND $2 GROUP BY sy.id,sy.name,sy.starts_on,g.id,g.code,g.name,g.sequence ORDER BY sy.starts_on DESC,g.sequence`,[from,to]);
  if(type==='students-by-section')return rows(`SELECT sy.name school_year,g.name grade_level,COALESCE(s.name,'Unassigned') section,count(*)::int students FROM enrollments e JOIN school_years sy ON sy.id=e.school_year_id JOIN grade_levels g ON g.id=e.grade_level_id LEFT JOIN sections s ON s.id=e.section_id WHERE e.enrollment_date BETWEEN $1 AND $2 AND e.status IN ('pending','enrolled') GROUP BY sy.id,sy.name,sy.starts_on,g.id,g.name,g.sequence,s.id,s.name ORDER BY sy.starts_on DESC,g.sequence,s.name`,[from,to]);
  if(type==='employee-attendance')return rows(`SELECT attendance_date,status,source,count(*)::int records,COALESCE(sum(minutes_late),0)::int minutes_late FROM employee_attendance_records WHERE archived_at IS NULL AND attendance_date BETWEEN $1 AND $2 GROUP BY attendance_date,status,source ORDER BY attendance_date DESC,status`,[from,to]);
  if(type==='student-attendance')return rows(`SELECT a.attendance_date,sy.name school_year,g.name grade_level,COALESCE(sec.name,'Unassigned') section,a.status,count(*)::int records,COALESCE(sum(a.minutes_late),0)::int minutes_late FROM student_attendance_records a JOIN enrollments e ON e.id=a.enrollment_id JOIN school_years sy ON sy.id=e.school_year_id JOIN grade_levels g ON g.id=e.grade_level_id LEFT JOIN sections sec ON sec.id=e.section_id WHERE a.archived_at IS NULL AND a.attendance_date BETWEEN $1 AND $2 GROUP BY a.attendance_date,sy.id,sy.name,g.id,g.name,g.sequence,sec.id,sec.name,a.status ORDER BY a.attendance_date DESC,g.sequence,sec.name,a.status`,[from,to]);
  if(type==='admissions-pipeline')return rows(`SELECT sy.name school_year,g.name grade_level,a.status,count(*)::int applications,count(*) FILTER(WHERE a.application_type='new_student')::int new_students,count(*) FILTER(WHERE a.application_type='returning_student')::int returning_students FROM admission_applications a JOIN school_years sy ON sy.id=a.school_year_id JOIN grade_levels g ON g.id=a.grade_level_id WHERE a.archived_at IS NULL AND a.created_at::date BETWEEN $1 AND $2 GROUP BY sy.id,sy.name,sy.starts_on,g.id,g.name,g.sequence,a.status ORDER BY sy.starts_on DESC,g.sequence,a.status`,[from,to]);
  if(type==='grading-progress')return rows(`SELECT sy.name school_year,g.name grade_level,gp.name grading_period,gb.status,count(*)::int gradebooks,count(sg.id)::int grade_entries,count(sg.final_grade)::int completed_grades,round(avg(sg.final_grade),2) average_grade FROM gradebooks gb JOIN grading_periods gp ON gp.id=gb.grading_period_id JOIN school_years sy ON sy.id=gp.school_year_id JOIN teaching_assignments ta ON ta.id=gb.teaching_assignment_id JOIN sections sec ON sec.id=ta.section_id JOIN grade_levels g ON g.id=sec.grade_level_id LEFT JOIN student_grades sg ON sg.gradebook_id=gb.id WHERE gb.updated_at::date BETWEEN $1 AND $2 GROUP BY sy.id,sy.name,sy.starts_on,g.id,g.name,g.sequence,gp.id,gp.name,gp.sequence,gb.status ORDER BY sy.starts_on DESC,g.sequence,gp.sequence,gb.status`,[from,to]);
  if(type==='notification-delivery')return rows(`SELECT n.category,n.priority,n.status,count(DISTINCT n.id)::int notifications,count(nr.user_id)::int recipients,count(nr.read_at)::int reads,CASE WHEN count(nr.user_id)=0 THEN 0 ELSE round(count(nr.read_at)::numeric*100/count(nr.user_id),1) END read_rate_percent FROM notifications n LEFT JOIN notification_recipients nr ON nr.notification_id=n.id WHERE n.created_at::date BETWEEN $1 AND $2 GROUP BY n.category,n.priority,n.status ORDER BY n.category,n.priority,n.status`,[from,to]);
  if(type==='events-summary')return rows(`SELECT ce.event_type,ce.status,COALESCE(c.name,'All campuses') campus,count(*)::int events,count(*) FILTER(WHERE ce.all_day)::int all_day_events FROM calendar_events ce LEFT JOIN campuses c ON c.id=ce.campus_id WHERE ce.archived_at IS NULL AND ce.starts_at::date<=$2 AND ce.ends_at::date>=$1 GROUP BY ce.event_type,ce.status,c.id,c.name ORDER BY ce.event_type,ce.status,c.name`,[from,to]);
  if(type==='workforce-headcount')return rows(`SELECT COALESCE(d.name,'Unassigned') department,COALESCE(et.name,'Unspecified') employee_type,e.employment_status,count(*)::int employees,count(*) FILTER(WHERE tp.id IS NOT NULL)::int teachers FROM employees e LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN employee_types et ON et.id=e.employee_type_id LEFT JOIN teacher_profiles tp ON tp.employee_id=e.id AND tp.archived_at IS NULL WHERE e.archived_at IS NULL AND e.hire_date<=$1 GROUP BY d.id,d.name,et.id,et.name,e.employment_status ORDER BY d.name NULLS LAST,et.name,e.employment_status`,[to]);
  throw new Error('UNKNOWN_REPORT')
 }
}export const reportingRepository=new ReportingRepository();
