import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('../auth/AuthContext',()=>({useAuth:()=>({has:()=>true})}));
import { Academics } from './Academics';

const activeYear={id:'year-active',version:2,name:'SY 2026–2027',startsOn:'2026-06-01',endsOn:'2027-03-31',status:'active',termCount:1,sectionCount:1,eventCount:1,createdAt:'2026-01-01'};
const plannedYear={id:'year-planned',version:1,name:'SY 2027–2028',startsOn:'2027-06-01',endsOn:'2028-03-31',status:'planned',termCount:1,sectionCount:1,eventCount:1,createdAt:'2027-01-01'};
const detail={schoolYear:plannedYear,currentActive:{id:activeYear.id,name:activeYear.name},terms:[{id:'term',version:1,name:'First Quarter',code:'Q1',startsOn:'2027-06-01',endsOn:'2027-08-31',status:'planned'}],sections:[{id:'section',version:1,name:'Faith',code:'G1-FAITH',gradeLevelName:'Grade 1',campusName:'Main',capacity:30,enrolledCount:0,active:true}],events:[{id:'event',version:1,title:'Opening of Classes',eventType:'academic',startsAt:'2027-06-01T00:00:00Z',status:'planned'}],history:[]};

function mockApi(){vi.stubGlobal('fetch',vi.fn().mockImplementation(async(input:unknown,init?:RequestInit)=>{const url=String(input);let body:unknown={items:[]};if(url.endsWith('/academics/school-years'))body={items:[activeYear,plannedYear]};else if(url.includes('/school-years/year-planned/detail'))body=detail;else if(url.includes('/school-years/year-planned/activate')&&init?.method==='POST')body={schoolYear:{...plannedYear,status:'active'},closedSchoolYear:activeYear};return{ok:true,status:init?.method==='POST'?201:200,json:async()=>body}}))}

describe('Academics School Year workspace',()=>{
  beforeEach(()=>mockApi());afterEach(()=>{cleanup();vi.unstubAllGlobals()});
  it('keeps year-dependent configuration out of the top-level navigation',async()=>{render(<Academics/>);expect(await screen.findByRole('table')).toBeInTheDocument();const nav=screen.getByRole('navigation',{name:'Academic configuration areas'});expect(within(nav).queryByRole('button',{name:'Terms'})).not.toBeInTheDocument();expect(within(nav).queryByRole('button',{name:'Sections'})).not.toBeInTheDocument();expect(within(nav).queryByRole('button',{name:'Calendar'})).not.toBeInTheDocument();expect(within(nav).getByRole('button',{name:'School Years'})).toBeInTheDocument()});
  it('marks exactly the selected Academic Structure tab',async()=>{render(<Academics/>);await screen.findByRole('table');const nav=screen.getByRole('navigation',{name:'Academic configuration areas'}),years=within(nav).getByRole('button',{name:'School Years'}),grades=within(nav).getByRole('button',{name:'Grade Levels'});expect(years).toHaveAttribute('aria-selected','true');fireEvent.click(grades);expect(grades).toHaveAttribute('aria-selected','true');expect(years).toHaveAttribute('aria-selected','false')});
  it('creates School Years without exposing a status selector',async()=>{render(<Academics/>);fireEvent.click(await screen.findByRole('button',{name:'Add School Year'}));const dialog=screen.getByRole('dialog');expect(within(dialog).getByText(/created as/)).toHaveTextContent('Planned');expect(within(dialog).queryByLabelText('Status')).not.toBeInTheDocument();expect(within(dialog).getByLabelText('School Year')).toBeInTheDocument()});
  it('manages Terms, Sections, and Calendar inside the selected School Year',async()=>{render(<Academics/>);fireEvent.click(await screen.findByText('SY 2027–2028'));const dialog=await screen.findByRole('dialog');expect(within(dialog).getByRole('button',{name:'Terms (1)'})).toBeInTheDocument();expect(within(dialog).getByRole('button',{name:'Sections (1)'})).toBeInTheDocument();expect(within(dialog).getByRole('button',{name:'Calendar (1)'})).toBeInTheDocument();fireEvent.click(within(dialog).getByRole('button',{name:'Terms (1)'}));expect(within(dialog).getByText('First Quarter')).toBeInTheDocument()});
  it('configures Grading Periods separately from Terms inside the School Year',async()=>{const period={id:'period',version:1,name:'First Grading Period',code:'GP1',academicTermName:'First Quarter',startsOn:'2027-06-01',endsOn:'2027-08-15',status:'open',weight:1};vi.stubGlobal('fetch',vi.fn().mockImplementation(async(input:unknown)=>{const url=String(input),body=url.endsWith('/academics/school-years')?{items:[plannedYear]}:url.includes('/school-years/year-planned/detail')?{...detail,gradingPeriods:[period]}:{items:[]};return{ok:true,status:200,json:async()=>body}}));render(<Academics/>);fireEvent.click(await screen.findByText('SY 2027–2028'));const dialog=await screen.findByRole('dialog');fireEvent.click(within(dialog).getByRole('button',{name:'Grading Periods (1)'}));expect(within(dialog).getByText('First Grading Period')).toBeInTheDocument();expect(within(dialog).getByText('First Quarter')).toBeInTheDocument()});
  it('confirms that activation closes the actual current active School Year',async()=>{render(<Academics/>);fireEvent.click(await screen.findByText('SY 2027–2028'));const detailDialog=await screen.findByRole('dialog');fireEvent.click(within(detailDialog).getByRole('button',{name:'Activate School Year'}));const confirmation=await screen.findByRole('dialog');expect(within(confirmation).getByText('SY 2026–2027')).toBeInTheDocument();expect(within(confirmation).getByText('SY 2027–2028')).toBeInTheDocument()});
});
