import { KeyRound, UserRound } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useAuth } from '../auth/AuthContext';
import { Card } from '../components/ui';
import { ApiError } from '../lib/api';

export function Account() {
  const { user,changePassword } = useAuth(); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const next = String(data.get('newPassword')); setError(''); setMessage(''); if (next !== data.get('confirmPassword')) { setError('New passwords do not match.'); return; } setSaving(true); try { await changePassword(String(data.get('currentPassword')),next); form.reset(); setMessage('Your password has been changed. Other sessions were signed out.'); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Unable to change password'); } finally { setSaving(false); } };
  return <div className="page account-page"><div className="page-heading"><div><span className="eyebrow">Account</span><h1>Your school account</h1><p>Review your identity and keep your sign-in secure.</p></div></div><div className="account-grid"><Card className="admin-section"><div className="admin-title"><UserRound /><div><h2>{user?.displayName}</h2><p>{user?.loginIdentifier}</p></div></div><dl><dt>Account type</dt><dd>{user?.accountType}</dd><dt>Recovery email</dt><dd>{user?.email||'Not configured'}</dd><dt>Assigned roles</dt><dd>{user?.roles.join(', ') || 'No assigned role'}</dd></dl></Card><Card className="admin-section"><div className="admin-title"><KeyRound /><div><h2>Change password</h2><p>Use 12+ characters with uppercase, lowercase, number, and symbol characters.</p></div></div>{error && <div className="form-error" role="alert">{error}</div>}{message && <div className="form-success" role="status">{message}</div>}<form className="stack-form" onSubmit={submit}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required /></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={12} required /></label><label>Confirm new password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} required /></label><button className="button" disabled={saving}>{saving ? 'Saving…' : 'Change password'}</button></form></Card></div></div>;
}
