import{KeyRound,MapPin,MonitorSmartphone,Plus,Power,ShieldOff}from'lucide-react';
import{useCallback,useEffect,useState,type FormEvent}from'react';
import{Card,Modal,Spinner}from'../components/ui';import{api,apiErrorMessage}from'../lib/api';
type Terminal={id:string;code:string;name:string;location:string|null;description:string|null;status:'active'|'inactive'|'revoked';campusId:string|null;campusName:string|null;lastSeenAt:string|null;lastSyncAt:string|null;assignedDeviceIdentifier:string|null;lastHeartbeatAt:string|null;pendingCount:number|null;syncState:string|null;applicationVersion:string|null;version:number};
type Device={id:string;deviceIdentifier:string;status:'active'|'revoked';provisionedBy:string;provisionedAt:string;lastSeenAt:string|null;lastSyncAt:string|null;lastHeartbeatAt:string|null;applicationVersion:string;terminalName:string;pendingCount:number;failedCount:number;syncState:string;revokedAt:string|null;revocationReason:string|null};
type Token={id:string;terminalId:string;displaySuffix:string;status:string;createdAt:string;expiresAt:string;consumedAt:string|null;createdBy:string};type Campus={id:string;name:string};
const when=(value:string|null)=>value?new Date(value).toLocaleString('en-PH'):'Never';const short=(value:string)=>`${value.slice(0,8)}…${value.slice(-4)}`;
export function AttendanceTerminals(){const[items,setItems]=useState<Terminal[]>([]),[devices,setDevices]=useState<Device[]>([]),[tokens,setTokens]=useState<Token[]>([]),[campuses,setCampuses]=useState<Campus[]>([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Terminal|null>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[generated,setGenerated]=useState<{provisioningCode:string;expiresAt:string}|null>(null),[revoking,setRevoking]=useState<Device|null>(null);
 const load=useCallback(async()=>{try{const x=await api<{terminals:Terminal[];campuses:Campus[];devices:Device[];provisioningTokens:Token[]}>('/attendance-terminals/admin');setItems(x.terminals);setCampuses(x.campuses);setDevices(x.devices);setTokens(x.provisioningTokens);setError('')}catch(e){setError(apiErrorMessage(e,'Unable to load terminals'))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),body={name:String(f.get('name')),location:String(f.get('location'))||null,campusId:String(f.get('campusId'))||null,description:String(f.get('description'))||null,...(editing?{version:editing.version}:{code:String(f.get('code'))})};setBusy(true);try{await api(editing?`/attendance-terminals/${editing.id}`:'/attendance-terminals',{method:editing?'PATCH':'POST',body:JSON.stringify(body)});setEditing(undefined);await load()}catch(x){setError(apiErrorMessage(x,'Unable to save terminal'))}finally{setBusy(false)}};
 const status=async(x:Terminal,next:Terminal['status'])=>{try{await api(`/attendance-terminals/${x.id}/status`,{method:'POST',body:JSON.stringify({status:next})});await load()}catch(e){setError(apiErrorMessage(e,'Unable to change terminal status'))}};
 const generate=async(terminalId:string)=>{setBusy(true);try{const response=await api<{item:{provisioningCode:string;expiresAt:string}}>(`/attendance-terminals/${terminalId}/provisioning-tokens`,{method:'POST',body:'{}'});setGenerated(response.item);await load()}catch(e){setError(apiErrorMessage(e,'Unable to generate provisioning code'))}finally{setBusy(false)}};
 const revoke=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!revoking)return;const f=new FormData(e.currentTarget);setBusy(true);try{await api(`/attendance-terminals/devices/${revoking.id}/revoke`,{method:'POST',body:JSON.stringify({reason:String(f.get('reason'))})});setRevoking(null);await load()}catch(x){setError(apiErrorMessage(x,'Unable to revoke device'))}finally{setBusy(false)}};
 if(loading)return <div className="page"><Spinner label="Loading attendance terminals"/></div>;
 return <div className="page"><div className="page-heading"><div><span className="eyebrow">System administration</span><h1>Attendance terminals</h1><p>Manage logical terminal locations and their independently revocable kiosk devices.</p></div><button className="button inline-button" onClick={()=>setEditing(null)}><Plus/>Create terminal</button></div>{error&&<div className="form-error" role="alert">{error}</div>}
 <Card className="admin-section"><div className="admin-title"><MonitorSmartphone/><div><h2>Registered terminals</h2><p>Create a provisioning code directly for the terminal a device should operate.</p></div></div><div className="table-wrap"><table><thead><tr><th>Terminal</th><th>Campus / location</th><th>Status</th><th>Device / sync</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>{x.code}</small></td><td>{x.campusName??'No campus'}<small><MapPin/> {x.location??'No location'}</small></td><td><span className={`status status--${x.status==='active'?'active':'archived'}`}>{x.status==='active'?'Enabled':x.status}</span></td><td>{x.assignedDeviceIdentifier?short(x.assignedDeviceIdentifier):'Not provisioned'}<small>{x.syncState??'No status'} · {x.pendingCount??0} queued</small></td><td><div className="row-actions"><button className="text-button" onClick={()=>setEditing(x)}>Edit</button><button className="text-button" disabled={x.status!=='active'||busy} onClick={()=>void generate(x.id)}><KeyRound/>Provision Device</button><button className="text-button" onClick={()=>void status(x,x.status==='active'?'inactive':'active')}><Power/>{x.status==='active'?'Disable':'Enable'}</button></div></td></tr>)}</tbody></table></div></Card>
 <Card className="admin-section"><div className="admin-title"><KeyRound/><div><h2>Provisioned devices</h2><p>Device credentials are displayed once at provisioning and can only be revoked, never retrieved.</p></div></div><div className="table-wrap"><table><thead><tr><th>Device</th><th>Terminal</th><th>Status</th><th>Last seen / sync</th><th>Actions</th></tr></thead><tbody>{devices.map(x=><tr key={x.id}><td><strong>{short(x.deviceIdentifier)}</strong><small>App {x.applicationVersion}</small></td><td>{x.terminalName}<small>{x.pendingCount} queued · {x.failedCount} failed</small></td><td>{x.status}</td><td>{when(x.lastSeenAt)}<small>Sync {when(x.lastSyncAt)}</small></td><td>{x.status==='active'&&<button className="text-button danger" onClick={()=>setRevoking(x)}><ShieldOff/>Revoke</button>}</td></tr>)}</tbody></table></div></Card>
 <Card className="admin-section"><div className="admin-title"><KeyRound/><div><h2>Recent provisioning codes</h2><p>Short-lived, single-use codes. Plaintext is never retrievable.</p></div></div><div className="table-wrap"><table><thead><tr><th>Suffix</th><th>Status</th><th>Created by</th><th>Expires</th></tr></thead><tbody>{tokens.map(x=><tr key={x.id}><td>•••• {x.displaySuffix}</td><td>{x.status}</td><td>{x.createdBy}</td><td>{when(x.expiresAt)}</td></tr>)}</tbody></table></div></Card>
 <Modal open={editing!==undefined} title={editing?'Edit attendance terminal':'Create attendance terminal'} busy={busy} error={error} onClose={()=>setEditing(undefined)} footer={<button form="terminal-form" className="button" disabled={busy}>Save terminal</button>}><form id="terminal-form" className="modal-form" onSubmit={save}>{!editing&&<label>Terminal code<input name="code" required maxLength={60}/></label>}<label>Terminal name<input name="name" defaultValue={editing?.name} required/></label><label>Campus<select name="campusId" defaultValue={editing?.campusId??''}><option value="">No campus</option>{campuses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Location<input name="location" defaultValue={editing?.location??''}/></label><label className="wide">Description<textarea name="description" defaultValue={editing?.description??''}/></label></form></Modal>
 <Modal open={Boolean(generated)} title="Provisioning code" description="Enter or scan this code on web-2 before it expires. It is shown only once." onClose={()=>setGenerated(null)}>{generated&&<div className="provisioning-secret"><code>{generated.provisioningCode}</code><p>Expires {when(generated.expiresAt)}</p></div>}</Modal>
 <Modal open={Boolean(revoking)} title="Revoke attendance terminal device" busy={busy} onClose={()=>setRevoking(null)} footer={<button form="revoke-device" className="button danger" disabled={busy}>Revoke device</button>}><form id="revoke-device" className="modal-form" onSubmit={revoke}><label>Reason<textarea name="reason" required minLength={3} maxLength={500}/></label></form></Modal></div>}
