import { CalendarDays, ChevronLeft, ChevronRight, Clock3, List, MapPin, Plus } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { useAuth } from '../auth/AuthContext';
import { EmptyState, Modal } from '../components/ui';
import { api, apiErrorMessage } from '../lib/api';

type CalendarEvent={id:string;title:string;eventType:string;startsAt:string;endsAt:string;allDay:boolean;location:string|null;description:string|null;status:string;campusId:string|null;campusName:string|null;schoolYearId:string|null;schoolYearName:string|null};
type Choice={id:string;name:string;status?:string;startsOn?:string;endsOn?:string;schoolId?:string};
const types=['academic','holiday','administrative','community','other'] as const;
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());
const ymd=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const monthRange=(cursor:Date)=>({from:ymd(new Date(cursor.getFullYear(),cursor.getMonth(),1)),to:ymd(new Date(cursor.getFullYear(),cursor.getMonth()+1,0))});
const dayKey=(iso:string)=>ymd(new Date(iso));
const formatTime=(item:CalendarEvent)=>item.allDay?'All day':`${new Date(item.startsAt).toLocaleTimeString('en-PH',{hour:'numeric',minute:'2-digit'})} – ${new Date(item.endsAt).toLocaleTimeString('en-PH',{hour:'numeric',minute:'2-digit'})}`;

export function CalendarExperience(){
  const{has}=useAuth();
  const[cursor,setCursor]=useState(()=>new Date());const[view,setView]=useState<'month'|'agenda'>('month');const[events,setEvents]=useState<CalendarEvent[]>([]);const[years,setYears]=useState<Choice[]>([]);const[campuses,setCampuses]=useState<Choice[]>([]);const[type,setType]=useState('');const[campusId,setCampusId]=useState('');const[selected,setSelected]=useState<CalendarEvent>();const[showCreate,setShowCreate]=useState(false);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
  const range=useMemo(()=>monthRange(cursor),[cursor]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams({...range,...(type&&{eventType:type}),...(campusId&&{campusId})});const[context,response]=await Promise.all([api<{schoolYears:Choice[];campuses:Choice[]}>('/calendar/context'),api<{items:CalendarEvent[]}>(`/calendar/events?${params}`)]);setYears(context.schoolYears);setCampuses(context.campuses);setEvents(response.items)}catch(cause){setError(apiErrorMessage(cause,'Unable to load the school calendar'))}finally{setLoading(false)}},[range,type,campusId]);
  useEffect(()=>{void load()},[load]);
  const weeks=useMemo(()=>{const first=new Date(cursor.getFullYear(),cursor.getMonth(),1);const start=new Date(first);start.setDate(first.getDate()-first.getDay());return Array.from({length:42},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);const key=ymd(date);return{date,key,current:date.getMonth()===cursor.getMonth(),today:key===ymd(new Date()),items:events.filter(item=>dayKey(item.startsAt)<=key&&dayKey(item.endsAt)>=key)}})},[cursor,events]);
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const startsAt=new Date(String(form.get('startsAt'))).toISOString();const endsAt=new Date(String(form.get('endsAt'))).toISOString();setSaving(true);setError('');try{await api('/academics/events',{method:'POST',body:JSON.stringify({schoolId:String(form.get('schoolId')),campusId:String(form.get('campusId'))||null,schoolYearId:String(form.get('schoolYearId'))||null,academicTermId:null,title:String(form.get('title')).trim(),eventType:String(form.get('eventType')),startsAt,endsAt,allDay:form.get('allDay')==='on',location:String(form.get('location')).trim()||null,description:String(form.get('description')).trim()||null,status:String(form.get('status'))})});setShowCreate(false);await load()}catch(cause){setError(apiErrorMessage(cause,'Unable to create event'))}finally{setSaving(false)}};
  const activeYear=years.find(item=>item.status==='active')??years[0];
  return <div className="calendar-page"><header className="calendar-heading"><div><h1>School calendar</h1><p>One view of academic dates, holidays, activities, and community events across MMSC.</p></div>{has('academic.calendar.manage')&&<button className="button inline-button" onClick={()=>setShowCreate(true)}><Plus/>New event</button>}</header>{error&&<div className="form-error" role="alert">{error}</div>}
    <section className="calendar-toolbar" aria-label="Calendar controls"><div className="calendar-period"><button aria-label="Previous month" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><ChevronLeft/></button><button className="today-button" onClick={()=>setCursor(new Date())}>Today</button><button aria-label="Next month" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><ChevronRight/></button><h2>{cursor.toLocaleDateString('en-PH',{month:'long',year:'numeric'})}</h2></div><div className="calendar-filters"><select aria-label="Event type" value={type} onChange={e=>setType(e.target.value)}><option value="">All event types</option>{types.map(item=><option key={item} value={item}>{label(item)}</option>)}</select><select aria-label="Campus" value={campusId} onChange={e=>setCampusId(e.target.value)}><option value="">All campuses</option>{campuses.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="calendar-view-switch" aria-label="Calendar view"><button className={view==='month'?'active':''} aria-pressed={view==='month'} onClick={()=>setView('month')}><CalendarDays/>Month</button><button className={view==='agenda'?'active':''} aria-pressed={view==='agenda'} onClick={()=>setView('agenda')}><List/>Agenda</button></div></div></section>
    {loading?<div className="calendar-skeleton" aria-label="Loading calendar">{Array.from({length:14},(_,i)=><span key={i}/>)}</div>:events.length===0?<EmptyState title="No events this month" message="Published school activities and important dates will appear here."/>:view==='month'?<section className="calendar-month" aria-label={`${cursor.toLocaleDateString('en-PH',{month:'long',year:'numeric'})} calendar`}><div className="calendar-weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-grid">{weeks.map(day=><article key={day.key} className={`${day.current?'':'outside'} ${day.today?'today':''}`}><time dateTime={day.key}>{day.date.getDate()}</time><div>{day.items.slice(0,3).map(item=><button key={item.id} className={`event-chip type-${item.eventType}`} onClick={()=>setSelected(item)}><span>{item.allDay?'':new Date(item.startsAt).toLocaleTimeString('en-PH',{hour:'numeric',minute:'2-digit'})}</span>{item.title}</button>)}{day.items.length>3&&<small>+{day.items.length-3} more</small>}</div></article>)}</div></section>:<section className="calendar-agenda">{events.map(item=><button key={item.id} onClick={()=>setSelected(item)}><time><strong>{new Date(item.startsAt).toLocaleDateString('en-PH',{day:'2-digit'})}</strong><span>{new Date(item.startsAt).toLocaleDateString('en-PH',{weekday:'short'})}</span></time><i className={`type-${item.eventType}`}/><span><strong>{item.title}</strong><small>{formatTime(item)}{item.location?` · ${item.location}`:''}</small></span><em>{label(item.eventType)}</em></button>)}</section>}
    <Modal open={Boolean(selected)} title={selected?.title??'Event'} description={selected?label(selected.eventType):undefined} onClose={()=>setSelected(undefined)} footer={<button className="button" onClick={()=>setSelected(undefined)}>Close</button>}>{selected&&<div className="calendar-detail"><p><Clock3/>{new Date(selected.startsAt).toLocaleDateString('en-PH',{weekday:'long',month:'long',day:'numeric',year:'numeric'})} · {formatTime(selected)}</p>{selected.location&&<p><MapPin/>{selected.location}{selected.campusName?` · ${selected.campusName}`:''}</p>}<p>{selected.description||'No additional event details.'}</p>{has('academic.calendar.manage')&&selected.status!=='published'&&<span className="status-badge">{label(selected.status)} preview</span>}</div>}</Modal>
    <Modal open={showCreate} title="Create calendar event" description="Add an event to the authoritative MMSC calendar." size="large" busy={saving} error={error} onClose={()=>setShowCreate(false)} footer={<><button className="text-button" onClick={()=>setShowCreate(false)}>Cancel</button><button form="calendar-create" className="button" disabled={saving}>{saving?'Creating…':'Create event'}</button></>}><form id="calendar-create" className="modal-form" onSubmit={create}><label>School<input name="schoolId" value={(activeYear as Choice&{schoolId?:string})?.schoolId??''} readOnly required placeholder="Configure a school year first"/></label><label>School year<select name="schoolYearId" defaultValue={activeYear?.id??''}><option value="">School-wide</option>{years.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Campus<select name="campusId"><option value="">All campuses</option>{campuses.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Event type<select name="eventType" defaultValue="academic">{types.map(item=><option key={item} value={item}>{label(item)}</option>)}</select></label><label className="wide">Title<input name="title" required maxLength={200}/></label><label>Starts<input name="startsAt" type="datetime-local" required/></label><label>Ends<input name="endsAt" type="datetime-local" required/></label><label className="check-field"><input name="allDay" type="checkbox"/>All-day event</label><label>Status<select name="status" defaultValue="planned"><option value="planned">Planned</option><option value="published">Published</option><option value="cancelled">Cancelled</option></select></label><label className="wide">Location<input name="location" maxLength={200}/></label><label className="wide">Description<textarea name="description" maxLength={2000}/></label></form></Modal>
  </div>
}
