/* eslint-disable react-hooks/exhaustive-deps -- Clinic route changes intentionally trigger a fresh repository snapshot. */
import{AlertTriangle,ArrowRight,Boxes,CheckCircle2,ClipboardPlus,Search,Stethoscope,UserRound}from'lucide-react';import{FormEvent,useEffect,useState}from'react';import{useLocation,useNavigate}from'react-router-dom';import{EmptyState,Spinner}from'../components/ui';import{api,apiErrorMessage}from'../lib/api';
import{useAuth}from'../auth/AuthContext';
import{ClinicHealthRecords}from'./ClinicHealthRecords';
import{ClinicConsultation}from'./ClinicConsultation';
import{ClinicInventory}from'./ClinicInventory';
import{ClinicScheduling}from'./ClinicScheduling';
import{ClinicOperationalAlerts}from'../components/ClinicOperationalAlerts';
import{ClinicReports}from'./ClinicReports';
type Queue={id:string;studentId:string;firstName:string;lastName:string;studentNumber:string;timeIn:string;queueStatus:string;chiefComplaint:string;gradeLevel:string;section:string|null};type Item={id:string;code:string;name:string;category:string;unit:string;stock:number;reorderLevel:number;nextExpiration:string|null;active:boolean};type Student={id:string;studentNumber:string;firstName:string;lastName:string;gradeLevel:string;section:string|null;profilePhotoUrl:string|null;alerts:{id:string;severity:string;title:string}[]};type Dash={metrics:{todayVisits:number;active:number;completed:number;followUpsDue:number;upcoming:number};queue:Queue[];inventoryAlerts:Item[]};
const title=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export function ClinicPortal(){const location=useLocation(),navigate=useNavigate(),{has}=useAuth(),mode=location.pathname.split('/')[2]||'dashboard';const[dash,setDash]=useState<Dash>(),[queue,setQueue]=useState<Queue[]>([]),[items,setItems]=useState<Item[]>([]),[students,setStudents]=useState<Student[]>([]),[selected,setSelected]=useState<Student>(),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{try{if(mode==='dashboard')setDash(await api<Dash>('/clinic/dashboard'));if(mode==='queue'||mode==='visits')setQueue((await api<{queue:Queue[]}>('/clinic/queue')).queue);if(mode==='inventory')setItems((await api<{items:Item[]}>('/clinic/items')).items);setError('')}catch(e){setError(apiErrorMessage(e,'Unable to load the clinic workspace'))}};useEffect(()=>{void load()},[mode]);
 const search=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{setStudents((await api<{students:Student[]}>(`/clinic/students?q=${encodeURIComponent(query)}`)).students);setError('')}catch(x){setError(apiErrorMessage(x,'Unable to search students'))}finally{setBusy(false)}};
 const visit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;setBusy(true);const f=new FormData(e.currentTarget);try{await api('/clinic/encounters',{method:'POST',body:JSON.stringify({studentId:selected.id,source:f.get('source'),chiefComplaint:f.get('complaint'),symptoms:String(f.get('symptoms')||'').split(',').map(x=>x.trim()).filter(Boolean),temperatureC:f.get('temperature')?Number(f.get('temperature')):undefined,assessment:f.get('assessment')||undefined})});setNotice('Visit started and added to the active queue.');setSelected(undefined);navigate('/clinic/queue');await load()}catch(x){setError(apiErrorMessage(x,'Unable to start the visit'))}finally{setBusy(false)}};
 const loading=(mode==='dashboard'&&!dash)||(mode==='inventory'&&!items.length&&busy);if(loading&&!error)return <div className="clinic-loading"><Spinner label="Opening the clinic workspace"/></div>;
 const headings:Record<string,[string,string]>={dashboard:['Clinic dashboard','Today’s care, queue, and medicine alerts at a glance.'],students:['Student lookup','Find an enrolled student and begin an authorized clinic visit.'],queue:['Visit queue','Students currently waiting or receiving clinic care.'],visits:['Daily transaction log','Search today’s consultations and open their complete clinical record.'],'health-records':['Health records','Access longitudinal student health information through Student Lookup.'],inventory:['Medicine & supplies','Current on-hand stock and expiration visibility.'],appointments:['Appointments','Scheduled clinic care will be managed in the appointments workflow.'],'follow-ups':['Follow-ups','Required return visits will be managed in the follow-up workflow.'],reports:['Clinic reports','Permission-scoped clinical operations reporting.']};const heading=headings[mode]??headings.dashboard;
 return <div className="clinic-page"><header className="clinic-page-heading"><div><h1>{heading[0]}</h1><p>{heading[1]}</p></div>{mode==='dashboard'&&has('clinic.encounter.manage')&&<button className="button" onClick={()=>navigate('/clinic/students')}><ClipboardPlus/>New visit</button>}</header>{error&&<div className="form-error" role="alert">{error}</div>}{notice&&<div className="clinic-notice"><CheckCircle2/>{notice}</div>}
 {mode==='dashboard'&&dash&&<><section className="clinic-metrics"><article><span>Today’s visits</span><strong>{dash.metrics.todayVisits}</strong><small>{dash.metrics.completed} completed</small></article><article><span>Waiting / active</span><strong>{dash.metrics.active}</strong><small>Across the live queue</small></article><article><span>Follow-ups due</span><strong>{dash.metrics.followUpsDue}</strong><small>Due today or earlier</small></article><article><span>Upcoming</span><strong>{dash.metrics.upcoming}</strong><small>Next seven days</small></article></section><div className="clinic-dashboard-grid"><QueueList rows={dash.queue} onOpen={id=>navigate(`/clinic/visits?encounter=${id}`)}/><section className="clinic-panel clinic-alerts"><header><div><h2>Medicine alerts</h2><p>Low, out-of-stock, or expired inventory.</p></div><Boxes/></header>{dash.inventoryAlerts.length?dash.inventoryAlerts.map(x=><article key={x.id}><AlertTriangle/><span><strong>{x.name}</strong><small>{x.stock} {x.unit} on hand · reorder at {x.reorderLevel}</small></span></article>):<EmptyState title="Inventory is healthy" message="No low-stock or expired items need attention."/>}</section></div><ClinicOperationalAlerts/></>}
 {mode==='queue'&&<QueueList rows={queue} onOpen={id=>navigate(`/clinic/visits?encounter=${id}`)}/>} {mode==='visits'&&<ClinicConsultation/>}
 {mode==='students'&&<><form className="clinic-search" onSubmit={search}><Search/><input aria-label="Student number or name" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Student number or full name"/><button className="button" disabled={busy||query.trim().length<2}>Search</button></form><section className="clinic-results">{students.map(s=><button key={s.id} disabled={!has('clinic.encounter.manage')} onClick={()=>setSelected(s)}><span className="clinic-avatar">{s.profilePhotoUrl?<img src={s.profilePhotoUrl} alt=""/>:<UserRound/>}</span><span><strong>{s.firstName} {s.lastName}</strong><small>{s.studentNumber} · {s.gradeLevel} {s.section||''}</small>{s.alerts?.map(a=><em key={a.id}><AlertTriangle/>{a.title}</em>)}</span>{has('clinic.encounter.manage')&&<ArrowRight/>}</button>)}</section>{!students.length&&<EmptyState title="Search the student directory" message="Use a student number or name. Results are limited to currently enrolled students."/>}{selected&&has('clinic.encounter.manage')&&<section className="clinic-consult"><header><div><h2>Start clinic visit</h2><p>{selected.firstName} {selected.lastName} · {selected.studentNumber}</p></div><button onClick={()=>setSelected(undefined)}>Close</button></header>{selected.alerts?.length>0&&<div className="clinic-critical"><AlertTriangle/><span><strong>Critical health information</strong>{selected.alerts.map(a=><small key={a.id}>{title(a.severity)} · {a.title}</small>)}</span></div>}<form onSubmit={visit}><label>Visit source<select name="source" defaultValue="self_initiated"><option value="self_initiated">Self-initiated</option><option value="teacher_referral">Teacher referral</option><option value="injury">Injury</option><option value="scheduled_visit">Scheduled visit</option><option value="follow_up">Follow-up</option><option value="other">Other</option></select></label><label className="wide">Chief complaint<textarea name="complaint" required maxLength={3000}/></label><label className="wide">Symptoms <small>Separate multiple symptoms with commas.</small><input name="symptoms" placeholder="Headache, fever"/></label><label>Temperature °C<input name="temperature" type="number" min="25" max="45" step="0.1"/></label><label>Initial assessment<textarea name="assessment" maxLength={5000}/></label><button className="button wide" disabled={busy}><Stethoscope/>Start visit</button></form></section>}</>}
 {mode==='inventory'&&<ClinicInventory/>}
 {mode==='health-records'&&<ClinicHealthRecords/>}
 {mode==='appointments'&&<ClinicScheduling mode="appointments"/>}
 {mode==='follow-ups'&&<ClinicScheduling mode="follow-ups"/>}
 {mode==='reports'&&<ClinicReports/>}</div>}
function QueueList({rows,onOpen}:{rows:Queue[];onOpen:(id:string)=>void}){return <section className="clinic-panel clinic-queue"><header><div><h2>Current queue</h2><p>Waiting, consulting, and observing.</p></div><Stethoscope/></header>{rows.length?rows.map(q=><article key={q.id}><time>{new Date(q.timeIn).toLocaleTimeString('en-PH',{hour:'numeric',minute:'2-digit'})}</time><span><strong>{q.firstName} {q.lastName}</strong><small>{q.gradeLevel} {q.section||''} · {q.chiefComplaint}</small></span><b>{title(q.queueStatus)}</b><button onClick={()=>onOpen(q.id)}>Open <ArrowRight/></button></article>):<EmptyState title="The active queue is clear" message="New visits appear here as soon as an encounter starts."/>}</section>}
