import{describe,expect,it}from'vitest';import{canCompleteEnrollmentCandidate,enrollmentCompletionPath,enrollmentListPath,enrollmentReadiness,isEnrollmentCandidateKind}from'../domain/enrollment-query';
describe('Enrollment queue query',()=>{it('keeps server pagination with actionable filters',()=>{expect(enrollmentListPath({search:'Ana Cruz',schoolYearId:'year',gradeLevelId:'grade',sectionId:'section',status:'actionable',applicationType:'new_student',sort:'newest',limit:25,offset:25})).toBe('/enrollments?search=Ana+Cruz&schoolYearId=year&gradeLevelId=grade&sectionId=section&status=actionable&applicationType=new_student&sort=newest&limit=25&offset=25')});it('omits empty filters',()=>{expect(enrollmentListPath({search:'',status:'',limit:25,offset:0})).toBe('/enrollments?limit=25&offset=0')})});
describe('Enrollment confirmation contract',()=>{it.each(['admission','enrollment']as const)('uses canonical candidate kind %s',kind=>{expect(enrollmentCompletionPath(kind,'record-id')).toBe(`/enrollments/candidates/${kind}/record-id/complete`)})});
describe('Enrollment candidate guard',()=>{it.each(['admission','enrollment'])('accepts %s',kind=>expect(isEnrollmentCandidateKind(kind)).toBe(true));it.each(['student','enrolled',undefined])('rejects noncanonical %s',kind=>expect(isEnrollmentCandidateKind(kind)).toBe(false))});
describe('Enrollment completion eligibility',()=>{
 it('allows an approved Admission for a manager',()=>expect(canCompleteEnrollmentCandidate({candidateKind:'admission',status:'approved'},true)).toBe(true));
 it('does not treat synthetic pending as a canonical Admission detail state',()=>expect(canCompleteEnrollmentCandidate({candidateKind:'admission',status:'pending'},true)).toBe(false));
 it('allows a pending persisted Enrollment for a manager',()=>expect(canCompleteEnrollmentCandidate({candidateKind:'enrollment',status:'pending'},true)).toBe(true));
 it('rejects an enrolled candidate and a view-only user',()=>{expect(canCompleteEnrollmentCandidate({candidateKind:'enrollment',status:'enrolled'},true)).toBe(false);expect(canCompleteEnrollmentCandidate({candidateKind:'admission',status:'approved'},false)).toBe(false)});
 it('reports each blocking readiness state accurately',()=>{const admission={candidateKind:'admission' as const,status:'approved'};expect(enrollmentReadiness(admission,true,1,0)).toBe('curriculum_missing');expect(enrollmentReadiness(admission,true,0,9)).toBe('sections_missing');expect(enrollmentReadiness(admission,false,1,9)).toBe('view_only');expect(enrollmentReadiness(admission,true,1,9)).toBe('ready');expect(enrollmentReadiness({candidateKind:'admission',status:'converted'},true,1,9)).toBe('not_completable')});
});
