import{ChevronLeft,ChevronRight,Download,FileSpreadsheet}from'lucide-react';
import{FormEvent,useCallback,useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext';
import{EmptyState,Spinner}from'../components/ui';
import{api,apiBaseUrl,apiErrorMessage}from'../lib/api';

const reports=[['current_loans','Current loans'],['overdue','Overdue books'],['borrowing_history','Borrowing history'],['inventory','Book inventory'],['exceptions','Lost / damaged books'],['visitor_logs','Library visitor logs'],['visitor_analytics','Visitor analytics'],['circulation_summary','Circulation summary']]as const;
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const today=()=>new Date().toISOString().slice(0,10);const ago=()=>{const d=new Date();d.setDate(d.getDate()-29);return d.toISOString().slice(0,10)};
type Row=Record<string,unknown>;

export function LibraryReports(){const{has}=useAuth(),[report,setReport]=useState<(typeof reports)[number][0]>('current_loans'),[from,setFrom]=useState(ago),[to,setTo]=useState(today),[patronType,setPatronType]=useState(''),[copyStatus,setCopyStatus]=useState(''),[items,setItems]=useState<Row[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');const limit=25;
 const params=useCallback((format:'json'|'csv'='json')=>{const q=new URLSearchParams({report,from,to,format,limit:String(limit),offset:String(offset)});if(patronType)q.set('patronType',patronType);if(copyStatus)q.set('copyStatus',copyStatus);return q},[copyStatus,from,offset,patronType,report,to]);
 const run=useCallback(async()=>{setBusy(true);try{const result=await api<{items:Row[];total:number}>(`/library/reports?${params()}`);setItems(result.items);setTotal(result.total);setError('')}catch(cause){setError(apiErrorMessage(cause,'Unable to run this Library report'))}finally{setBusy(false)}},[params]);useEffect(()=>{void run()},[run]);
 const keys=useMemo(()=>items[0]?Object.keys(items[0]):[],[items]);const submit=(event:FormEvent)=>{event.preventDefault();setOffset(0);void run()};const inventory=report==='inventory'||report==='exceptions';
 return <main className="library-circulation library-reports"><header><h1>Library reports</h1><p>Permission-scoped operational reports from authoritative Library records.</p></header><div className="library-report-layout"><nav aria-label="Library report catalog">{reports.map(([id,name])=><button key={id} className={report===id?'active':''} onClick={()=>{setReport(id);setOffset(0)}}>{name}</button>)}</nav><section className="library-report-workspace"><header><div><h2>{reports.find(x=>x[0]===report)?.[1]}</h2><p>{report.startsWith('visitor')?'Library visits only — this is not school attendance.':'Detailed records are bounded and server-filtered.'}</p></div>{has('report.export')&&<a className="text-button" href={`${apiBaseUrl}/library/reports?${params('csv')}`}><Download/>Export CSV</a>}</header><form className="library-catalog-filters" onSubmit={submit}><label>From<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label>{!inventory&&<label>Patron type<select value={patronType} onChange={e=>setPatronType(e.target.value)}><option value="">All patrons</option><option value="student">Students</option><option value="teacher">Teachers</option><option value="employee">Employees</option></select></label>}{inventory&&<label>Copy status<select value={copyStatus} onChange={e=>setCopyStatus(e.target.value)}><option value="">All statuses</option>{['available','checked_out','reserved','lost','damaged','under_repair','withdrawn'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label>}<button className="button" disabled={busy}>Run report</button></form>{error&&<div className="form-error" role="alert">{error}</div>}{busy&&!items.length?<Spinner label="Running Library report"/>:items.length?<><div className="library-report-summary"><FileSpreadsheet/><strong>{total.toLocaleString()}</strong><span>matching records</span></div><div className="library-catalog-table"><table><thead><tr>{keys.map(key=><th key={key}>{label(key)}</th>)}</tr></thead><tbody>{items.map((row,index)=><tr key={String(row.id??`${offset}-${index}`)}>{keys.map(key=><td key={key}>{row[key]==null?'—':String(row[key])}</td>)}</tr>)}</tbody></table><div className="library-pagination"><span>{offset+1}–{Math.min(offset+limit,total)} of {total}</span><button aria-label="Previous report page" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-limit))}><ChevronLeft/></button><button aria-label="Next report page" disabled={offset+limit>=total} onClick={()=>setOffset(offset+limit)}><ChevronRight/></button></div></div></>:<EmptyState title="No report records" message="Try a different report or date range. No placeholder data is generated."/>}</section></div></main>}
