import{BookCheck,BookOpen,BookUp,ClockAlert,Library,Settings,UsersRound}from'lucide-react';
import{FormEvent,useEffect,useState,type ReactNode}from'react';
import{useLocation}from'react-router-dom';
import{EmptyState,Spinner}from'../components/ui';
import{api,apiErrorMessage}from'../lib/api';
import{LibraryCatalog}from'./LibraryCatalog';
import{LibraryCheckin,LibraryCheckout,LibraryPatrons}from'./LibraryCirculation';
import{LibraryVisitors}from'./LibraryVisitors';
import{LibraryOverdue}from'./LibraryOverdue';
import{LibraryReports}from'./LibraryReports';
import{useAuth}from'../auth/AuthContext';

type Metrics={totalBookCopies:number;available:number;checkedOut:number;overdue:number;visitorsToday:number;currentlyInside:number;borrowedToday:number;returnedToday:number};type Dashboard={metrics:Metrics;circulation:{day:string;checkouts:number;returns:number;overdue:number}[];mostBorrowed:{title:string;loans:number}[];popularCategories:{label:string;loans:number}[];alerts:{lost:number;damaged:number;underRepair:number;staleVisitorSessions:number}};
type PolicyOverride={patronType:'student'|'teacher'|'employee';enabled:boolean;maximumActiveLoans:number;loanPeriodDays:number;maximumRenewals:number;gracePeriodDays:number;allowBorrowingWithOverdue:boolean};
type LibrarySettings={schoolId:string;defaultLoanDays:number;maximumRenewals:number;maximumActiveLoans:number;gracePeriodDays:number;allowBorrowingWithOverdue:boolean;overrides:PolicyOverride[];updatedAt:string};
const pageCopy:Record<string,[string,string,string,string]>={
  checkout:['Checkout','Issue an available copy to an eligible MMSC patron.','Checkout opens in Group 4','Catalog copies and patron eligibility must be implemented before loans can be issued.'],
  'check-in':['Check-in','Receive a borrowed copy and complete its active loan.','Check-in opens in Group 4','Circulation records are intentionally deferred until the catalog and copy foundation exists.'],
  catalog:['Catalog','Search and manage the Library collection.','Catalog management opens in Group 2','Books, authors, categories, publishers, and subjects will be introduced in the next Library group.'],
  patrons:['Patrons','Resolve borrowing eligibility from authoritative MMSC identities.','Patron lookup opens in Group 3','Library will reuse Students, Employees, and centralized credentials without copying identity records.'],
  visitors:['Visitors','Record entry and exit independently from attendance.','Visitor logging opens in Group 5','Visitor activity will use shared identity resolution but remain a separate Library domain.'],
  overdue:['Overdue','Review and manage loans that passed their due date.','Overdue management opens in Group 6','This workspace will activate after circulation transactions are implemented.'],
  reports:['Reports','Review permission-scoped Library operations.','Reports open in Group 7','Operational reporting will be calculated from authoritative Library transactions.'],
};
const metricCards=[['totalBookCopies','Total book copies',BookOpen],['available','Available',BookCheck],['checkedOut','Checked out',BookUp],['overdue','Overdue',ClockAlert],['visitorsToday','Visitors today',UsersRound],['currentlyInside','Currently inside',Library],['borrowedToday','Borrowed today',BookUp],['returnedToday','Returned today',BookCheck]]as const;

export function LibraryPortal(){
  const{has}=useAuth();
  const mode=useLocation().pathname.split('/')[2]||'dashboard';const[dashboard,setDashboard]=useState<Dashboard>();const metrics=dashboard?.metrics;const[settings,setSettings]=useState<LibrarySettings>();const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
  useEffect(()=>{setError('');if(mode==='dashboard')void api<Dashboard>('/library/dashboard').then(data=>setDashboard({...data,circulation:data.circulation??[],mostBorrowed:data.mostBorrowed??[],popularCategories:data.popularCategories??[],alerts:data.alerts??{lost:0,damaged:0,underRepair:0,staleVisitorSessions:0}})).catch(cause=>setError(apiErrorMessage(cause,'Unable to load the Library dashboard')));if(mode==='settings')void api<{settings:LibrarySettings}>('/library/settings').then(data=>setSettings(data.settings)).catch(cause=>setError(apiErrorMessage(cause,'Unable to load Library settings')))},[mode]);
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget),number=(name:string)=>Number(data.get(name)),checked=(name:string)=>data.get(name)==='on';const overrides=(['student','teacher','employee']as const).map(patronType=>({patronType,enabled:checked(`${patronType}.enabled`),maximumActiveLoans:number(`${patronType}.maximumActiveLoans`),loanPeriodDays:number(`${patronType}.loanPeriodDays`),maximumRenewals:number(`${patronType}.maximumRenewals`),gracePeriodDays:number(`${patronType}.gracePeriodDays`),allowBorrowingWithOverdue:checked(`${patronType}.allowBorrowingWithOverdue`)}));setBusy(true);setError('');setNotice('');try{const result=await api<{settings:LibrarySettings}>('/library/settings',{method:'PUT',body:JSON.stringify({defaultLoanDays:number('defaultLoanDays'),maximumRenewals:number('maximumRenewals'),maximumActiveLoans:number('maximumActiveLoans'),gracePeriodDays:number('gracePeriodDays'),allowBorrowingWithOverdue:checked('allowBorrowingWithOverdue'),overrides})});setSettings(result.settings);setNotice('Borrowing policies saved. Existing loan due dates were not changed.')}catch(cause){setError(apiErrorMessage(cause,'Unable to save Library settings'))}finally{setBusy(false)}};
  if(mode==='dashboard'&&!metrics&&!error)return <div className="library-loading"><Spinner label="Opening the Library workspace"/></div>;
  if(mode==='settings'&&!settings&&!error)return <div className="library-loading"><Spinner label="Loading Library settings"/></div>;
  if(mode==='dashboard')return <LibraryPage title="Library dashboard" description="Collection, circulation, and Library visits at a glance.">{error&&<div className="form-error" role="alert">{error}</div>}{metrics&&dashboard&&<><section className="library-metrics" aria-label="Library metrics">{metricCards.map(([key,label,Icon])=><article key={key}><Icon/><span><small>{label}</small><strong>{metrics[key]}</strong></span></article>)}</section><section className="library-dashboard-grid"><article><h2>Seven-day circulation</h2><div className="library-trend">{dashboard.circulation.map(x=><div key={x.day}><span>{new Date(x.day).toLocaleDateString(undefined,{weekday:'short'})}</span><i><b style={{height:`${Math.max(4,Math.min(100,(x.checkouts+x.returns)*10))}%`}}/></i><small>{x.checkouts} out · {x.returns} in</small></div>)}</div></article><article><h2>Operational alerts</h2><dl className="library-alerts"><div><dt>Lost</dt><dd>{dashboard.alerts.lost}</dd></div><div><dt>Damaged</dt><dd>{dashboard.alerts.damaged}</dd></div><div><dt>Under repair</dt><dd>{dashboard.alerts.underRepair}</dd></div><div><dt>Open since yesterday</dt><dd>{dashboard.alerts.staleVisitorSessions}</dd></div></dl></article><article><h2>Most borrowed · 30 days</h2>{dashboard.mostBorrowed.length?<ol>{dashboard.mostBorrowed.map(x=><li key={x.title}><span>{x.title}</span><strong>{x.loans}</strong></li>)}</ol>:<p>No checkouts in this period.</p>}</article><article><h2>Popular categories · 30 days</h2>{dashboard.popularCategories.length?<ol>{dashboard.popularCategories.map(x=><li key={x.label}><span>{x.label}</span><strong>{x.loans}</strong></li>)}</ol>:<p>No categorized circulation in this period.</p>}</article></section></>}</LibraryPage>;
  if(mode==='settings')return <LibraryPage title="Library settings" description="Default borrowing policy with optional Student, Teacher, and Employee overrides.">{error&&<div className="form-error" role="alert">{error}</div>}{notice&&<div className="form-success" role="status">{notice}</div>}{settings&&<form className="library-settings library-policy-form" onSubmit={save}><fieldset disabled={!has('library.settings.manage')||busy}><legend>Default policy</legend><div className="library-policy-grid"><label>Maximum active loans<input name="maximumActiveLoans" type="number" min="1" max="100" defaultValue={settings.maximumActiveLoans} required/></label><label>Loan period (days)<input name="defaultLoanDays" type="number" min="1" max="90" defaultValue={settings.defaultLoanDays} required/></label><label>Maximum renewals<input name="maximumRenewals" type="number" min="0" max="10" defaultValue={settings.maximumRenewals} required/></label><label>Grace period (days)<input name="gracePeriodDays" type="number" min="0" max="30" defaultValue={settings.gracePeriodDays} required/></label><label className="library-policy-check"><input name="allowBorrowingWithOverdue" type="checkbox" defaultChecked={settings.allowBorrowingWithOverdue}/> Allow borrowing with overdue items</label></div></fieldset><section><h2>Patron-type overrides</h2><p>Enable only when this patron type should differ from the default policy.</p>{settings.overrides.map(rule=><fieldset key={rule.patronType} disabled={!has('library.settings.manage')||busy}><legend>{rule.patronType[0].toUpperCase()+rule.patronType.slice(1)}</legend><label className="library-policy-check"><input name={`${rule.patronType}.enabled`} type="checkbox" defaultChecked={rule.enabled}/> Use this override</label><div className="library-policy-grid"><label>Maximum active loans<input name={`${rule.patronType}.maximumActiveLoans`} type="number" min="1" max="100" defaultValue={rule.maximumActiveLoans} required/></label><label>Loan period (days)<input name={`${rule.patronType}.loanPeriodDays`} type="number" min="1" max="365" defaultValue={rule.loanPeriodDays} required/></label><label>Maximum renewals<input name={`${rule.patronType}.maximumRenewals`} type="number" min="0" max="20" defaultValue={rule.maximumRenewals} required/></label><label>Grace period (days)<input name={`${rule.patronType}.gracePeriodDays`} type="number" min="0" max="30" defaultValue={rule.gracePeriodDays} required/></label><label className="library-policy-check"><input name={`${rule.patronType}.allowBorrowingWithOverdue`} type="checkbox" defaultChecked={rule.allowBorrowingWithOverdue}/> Allow borrowing with overdue items</label></div></fieldset>)}</section>{has('library.settings.manage')&&<div><button className="button" disabled={busy}><Settings/>{busy?'Saving…':'Save borrowing policies'}</button><small>Changes apply to future checkouts and renewals; existing due dates stay unchanged.</small></div>}</form>}</LibraryPage>;
  if(mode==='catalog')return <div className="library-page"><LibraryCatalog/></div>;
  if(mode==='checkout')return <LibraryCheckout/>;
  if(mode==='check-in')return <LibraryCheckin/>;
  if(mode==='patrons')return <LibraryPatrons/>;
  if(mode==='visitors')return <LibraryVisitors/>;
  if(mode==='overdue')return <LibraryOverdue/>;
  if(mode==='reports')return <LibraryReports/>;
  const copy=pageCopy[mode]??pageCopy.catalog!;return <LibraryPage title={copy[0]} description={copy[1]}><section className="library-empty"><EmptyState title={copy[2]} message={copy[3]}/></section></LibraryPage>;
}
function LibraryPage({title,description,children}:{title:string;description:string;children:ReactNode}){return <div className="library-page"><header className="library-page-heading"><h1>{title}</h1><p>{description}</p></header>{children}</div>}
