import { LockKeyhole } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useAuth } from '../auth/AuthContext';
import { api, ApiError } from '../lib/api';

export function Login() {
  const { login } = useAuth(); const [identifier, setIdentifier] = useState(''); const [password, setPassword] = useState(''); const [recovery,setRecovery]=useState(false);const[recoveryNotice,setRecoveryNotice]=useState('');
  const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setSubmitting(true); try { await login(identifier, password); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Unable to sign in'); } finally { setSubmitting(false); } };
  const forgot=async(event:FormEvent)=>{event.preventDefault();setSubmitting(true);setError('');try{const data=await api<{message:string}>('/auth/forgot-password',{method:'POST',body:JSON.stringify({identifier})});setRecoveryNotice(data.message);}catch(cause){setError(cause instanceof ApiError?cause.message:'Unable to start recovery');}finally{setSubmitting(false);}};
  return <main className="login-page"><section className="login-brand"><div><span className="eyebrow light">My Messiah School of Cavite</span><h1>One connected school community.</h1><p>Secure access to the MMSC Super App begins here.</p></div></section><section className="login-panel"><form className="login-card" onSubmit={recovery?forgot:submit}><img src="/mmsc-logo.jpg" alt="MMSC crest" /><span className="login-icon"><LockKeyhole /></span><h2>{recovery?'Recover your account':'Welcome back'}</h2><p>{recovery?'Enter the same Username or School ID you use to sign in.':'Use your Username, Student Number, Employee Number, or Parent/Guardian Number.'}</p>{error && <div className="form-error" role="alert">{error}</div>}{recoveryNotice&&<div className="form-success" role="status">{recoveryNotice}</div>}<label>Username or School ID<input autoComplete="username" required value={identifier} onChange={(e) => setIdentifier(e.target.value)} /></label>{!recovery&&<label>Password<input type="password" autoComplete="current-password" required value={password} onChange={(e) => setPassword(e.target.value)} /></label>}<button className="button" disabled={submitting}>{submitting ? 'Please wait…' : recovery?'Continue':'Sign in'}</button><button className="text-button login-recovery" type="button" onClick={()=>{setRecovery(value=>!value);setError('');setRecoveryNotice('');}}>{recovery?'Back to sign in':'Forgot password?'}</button><small>Contact your school administrator if you cannot access your account.</small></form></section></main>;
}
