import { AlertTriangle, Bell, CheckCheck, ChevronRight, Megaphone, Send } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { useAuth } from '../auth/AuthContext';
import { EmptyState, Modal, Spinner } from '../components/ui';
import { api, apiErrorMessage } from '../lib/api';

type InboxItem={id:string;title:string;body:string;category:string;priority:'normal'|'important'|'urgent';actionUrl:string|null;publishedAt:string;readAt:string|null};
type ManagedItem={id:string;title:string;status:string;version:number;recipientCount:number;targets:{label:string}[]};
type Context={roles:{code:string;name:string}[];gradeLevels:{id:string;name:string}[];sections:{id:string;name:string;gradeLevelName:string;schoolYearName:string}[];users:{id:string;displayName:string;email:string}[]};
const audiences:Record<string,string>={all_users:'Everyone',employees:'Employees',teachers:'Teachers',students:'Students',guardians:'Parents / guardians',role:'A role',grade_level:'A grade level',section:'A section',user:'A specific user'};

export function Notifications(){
  const{has}=useAuth(),canManage=has('notification.manage');
  const[items,setItems]=useState<InboxItem[]>([]),[managed,setManaged]=useState<ManagedItem[]>([]),[context,setContext]=useState<Context>();
  const[filter,setFilter]=useState<'all'|'unread'>('all'),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const[showCreate,setShowCreate]=useState(false),[busy,setBusy]=useState(false),[audience,setAudience]=useState('all_users');
  const load=useCallback(async()=>{setLoading(true);try{const inbox=await api<{items:InboxItem[]}>(`/notifications?filter=${filter}`);setItems(inbox.items);if(canManage){const[list,options]=await Promise.all([api<{items:ManagedItem[]}>('/notification-management'),api<Context>('/notification-management/context')]);setManaged(list.items);setContext(options)}setError('')}catch(cause){setError(apiErrorMessage(cause,'Unable to load notifications'))}finally{setLoading(false)}},[canManage,filter]);
  useEffect(()=>{void load()},[load]);
  const keyOptions=useMemo(()=>audience==='role'?context?.roles.map(x=>({key:x.code,label:x.name})):audience==='grade_level'?context?.gradeLevels.map(x=>({key:x.id,label:x.name})):audience==='section'?context?.sections.map(x=>({key:x.id,label:`${x.gradeLevelName} · ${x.name} · ${x.schoolYearName}`})):audience==='user'?context?.users.map(x=>({key:x.id,label:`${x.displayName} · ${x.email}`})):[],[audience,context]);
  const open=async(item:InboxItem)=>{if(!item.readAt){await api(`/notifications/${item.id}/read`,{method:'POST'});setItems(current=>current.map(entry=>entry.id===item.id?{...entry,readAt:new Date().toISOString()}:entry))}if(item.actionUrl)window.location.assign(item.actionUrl)};
  const readAll=async()=>{await api('/notifications/read-all',{method:'POST'});setItems(current=>current.map(item=>({...item,readAt:item.readAt??new Date().toISOString()})))};
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),key=String(form.get('targetKey')??''),expires=String(form.get('expiresAt')??'');setBusy(true);setError('');try{await api('/notification-management',{method:'POST',body:JSON.stringify({title:String(form.get('title')),body:String(form.get('body')),category:String(form.get('category')),priority:String(form.get('priority')),actionUrl:String(form.get('actionUrl')),expiresAt:expires?new Date(expires).toISOString():'',targets:[key?{type:audience,key}:{type:audience}]})});setShowCreate(false);await load()}catch(cause){setError(apiErrorMessage(cause,'Unable to save notification draft'))}finally{setBusy(false)}};
  const publish=async(item:ManagedItem)=>{setBusy(true);setError('');try{await api(`/notification-management/${item.id}/publish`,{method:'POST',body:JSON.stringify({version:item.version})});await load()}catch(cause){setError(apiErrorMessage(cause,'Unable to publish notification'))}finally{setBusy(false)}};
  return <div className="notifications-page">
    <header className="notifications-heading"><div><h1>Notification Center</h1><p>School messages, in one trusted inbox.</p></div>{canManage&&<button className="button" onClick={()=>setShowCreate(true)}><Megaphone/>New notification</button>}</header>
    {error&&<div className="form-error" role="alert">{error}</div>}
    <div className="notifications-tabs"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All</button><button className={filter==='unread'?'active':''} onClick={()=>setFilter('unread')}>Unread</button><button className="notifications-read-all" disabled={!items.some(item=>!item.readAt)} onClick={()=>void readAll()}><CheckCheck/>Mark all read</button></div>
    {loading?<div className="notifications-loading"><Spinner label="Loading notifications"/></div>:items.length?<section className="notification-list" aria-label="Your notifications">{items.map(item=><article key={item.id} className={`${item.readAt?'':'unread'} priority-${item.priority}`}><button className="notification-open" onClick={()=>void open(item)}><span className="notification-symbol">{item.priority==='urgent'?<AlertTriangle/>:<Bell/>}</span><span className="notification-copy"><span><b>{item.title}</b><time>{new Date(item.publishedAt).toLocaleString('en-PH',{dateStyle:'medium',timeStyle:'short'})}</time></span><p>{item.body}</p><small>{item.category.replaceAll('_',' ')}{!item.readAt?' · Unread':''}</small></span>{item.actionUrl&&<ChevronRight/>}</button></article>)}</section>:<EmptyState title={filter==='unread'?'You are all caught up':'No notifications yet'} message={filter==='unread'?'New school messages will appear here.':'Published messages addressed to you will appear here.'}/>} 
    {canManage&&<section className="notification-management"><header><div><h2>Publishing desk</h2><p>Draft and publish messages to authoritative MMSC audiences.</p></div></header>{managed.length?<div className="managed-list">{managed.map(item=><article key={item.id}><div><span className={`status status-${item.status}`}>{item.status}</span><h3>{item.title}</h3><p>{item.targets.map(target=>target.label).join(', ')}</p></div><span className="recipient-count">{item.status==='published'?`${item.recipientCount} recipient${item.recipientCount===1?'':'s'}`:'Not sent'}</span>{item.status==='draft'&&<button className="text-button" disabled={busy} onClick={()=>void publish(item)}><Send/>Publish</button>}</article>)}</div>:<EmptyState title="No messages created" message="Create a targeted draft, review it, then publish it to materialize recipients."/>}</section>}
    <Modal open={showCreate} title="New notification" description="Create a draft first. Publishing is a separate delivery step." error={error} busy={busy} onClose={()=>setShowCreate(false)} footer={<><button type="button" className="text-button" disabled={busy} onClick={()=>setShowCreate(false)}>Cancel</button><button form="notification-create" className="button" disabled={busy}>{busy?'Saving…':'Save draft'}</button></>}><form id="notification-create" className="modal-form" onSubmit={create}><label>Title<input name="title" required maxLength={180}/></label><label>Message<textarea name="body" required maxLength={5000} rows={5}/></label><div className="form-grid"><label>Category<select name="category" defaultValue="announcement"><option value="announcement">Announcement</option><option value="academic">Academic</option><option value="attendance">Attendance</option><option value="admissions">Admissions</option><option value="event">Event</option><option value="emergency">Emergency</option><option value="general">General</option></select></label><label>Priority<select name="priority" defaultValue="normal"><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></label></div><label>Audience<select value={audience} onChange={event=>setAudience(event.target.value)}>{Object.entries(audiences).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{keyOptions&&keyOptions.length>0&&<label>Recipient group<select name="targetKey" required defaultValue=""><option value="">Select audience…</option>{keyOptions.map(option=><option key={option.key} value={option.key}>{option.label}</option>)}</select></label>}<label>Open link inside MMSC<input name="actionUrl" placeholder="/student or /academics" pattern="/(?!/).*"/></label><label>Expires at<input name="expiresAt" type="datetime-local"/></label></form></Modal>
  </div>
}
